### ISSUE TITLE
Kernel Density Estimate

### ISSUE THREAD

**Issue by dantleech** [markrogoyski/math-php#1]
Would it be possible to add a [Kernel Density Estimate](https://en.wikipedia.org/wiki/Kernel_density_estimation)?

Here is one I ported from the SciPy library: https://github.com/phpbench/phpbench/blob/master/lib/Math/Kde.php

This library looks great btw.

**Comment by markrogoyski** [comment]
Thanks for the input. I'll add it to my roadmap of features.

**Comment by Beakerboy** [comment]
How does this look?

`<?php
namespace MathPHP\Probability\Distribution\Continuous;
use MathPHP\Probability\Distribution\Continuous\StandardNormal;
class KDE
{
    public function __construct(array $data, $h = null, callable $kernel = null) {
        $this->data = $data;
        $n = count($data);
        if ($h === null) {
            $h = (4 * stdev($data) ** 5 / 3 / $n) ** .2;
        } else {
            $this->h = $h;
        }
        if ($kernel === null) {
            $this->kernel = Continuous::StandardNormal($x);
        } else {
            $this->h = $h;
        }
    }
    
    public function __call($x)
    {
        $n = count($this->data);
        
        // Scale data to (x - xi) / h and evaluate with the kernel function
        $scale1 = Single::subtract($this->data, $x);
        $scale2 = Single::divide($scale1, -1 * $this->h);
        array_walk($scale2, $this->kernel);
        return 1 / $n / $this->h * array_sum($scale2);
    }
}`

**Comment by markrogoyski** [comment]
@Beakerboy Thanks for starting on this!
I think you can make an argument for putting it in ```Probability\Distribution\Continuous``` like you did, or perhaps in ```Statistics\RandomVariable```. Another option might be like ```SignalProcessing``` or wherever we decide stuff like FFT should go.

**Comment by Beakerboy** [comment]
My only argument against `Probability\Distribution\Continuous` is that unlike all the other classes in that namespace, it cannot inherit the Continuous class. I think adding it as a class within `Statistics` makes the most sense since `RandomVariable` is a class of static methods.

**Comment by markrogoyski** [comment]
@dantleech Pull request and continuing discussion: https://github.com/markrogoyski/math-php/pull/240

**Comment by Beakerboy** [comment]
I was basing my implementation on the process-flow used in matlab. There you assign the bandwidth and kernel when loading the data, then evaluate with your choice of X. We can do it however you want.

**Comment by Beakerboy** [comment]
1D Kernel Density is complete. If you want multidimensional, you can add that to the features list.

**Comment by markrogoyski** [comment]
Kernel density estimation has been implemented in [v0.33.0](https://github.com/markrogoyski/math-php/releases/tag/v0.33.0). Thank you to @Beakerboy for leading the implementation.

Apologies that it took a year to implement.

**Comment by dantleech** [comment]
Thanks both!
