### ISSUE TITLE
Performance expectations for iterative functions

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#103]
Some of the iterative functions I've been working on can have results from very large to very small. When developing unit tests, what would you like for the tolerance? I think a relative error makes most sense, especially since a value could be 1e-6. Having the unit test check if it's within .0001 is meaningless. Should I set some sort of tolerance as a constant in the unit test class? I was thinking 0.0001% might be a good place to start.

**Comment by markrogoyski** [comment]
One thing you can do is add the tolerance as a parameter provided by the data provider, so each test data provides its own tolerance.

For example:
```
/**
 * dataProvider dataProviderForTest
 */
public function testSomething($x, $expected, $tol)
{
    $this->assertEquals($expected, Class::function($x), '', $tol);
}

public function dataProviderForTest()
{
    return [
        [5, 0.543, 0.001],
        [9, 0.0000342, 0.0000001],
    ];
}
```

**Comment by Beakerboy** [comment]
I'm currently testing it like this:

    public function testHypergeometric($a, $b, $c, $z, $expected)
    {
        $actual = Special::hypergeometric($a, $b, $c, $z);
        $tol = .0000001 * $expected;
        $this->assertEquals($expected, $actual, '', $tol);
    }

I'm fine with whatever you like. What got me thinking about this is, if I were getting a project and wanted to know how accurate things were, having individual tolerances appears like someone if tweaking the test to pass. If a universal performance expectation is set, the algorithm will have to be designed to meet the expectation.

**Comment by markrogoyski** [comment]
OK. That makes sense. Tests should provide confidence that everything works as expected. Your way seems like a good idea.

The one instance that comes to mind for setting individual tolerances is when you are using various 3rd party test data, and they round the results or something.
