### ISSUE TITLE
Build an abstract class for numerical integration

### ISSUE THREAD

**Issue by jakobsandberg** [markrogoyski/math-php#104]
I'm building out other numerical integration techniques (simpons rule, midpoint rule, etc.) and they'll all very similar to the Trapezoidal rule.

I'm thinking of making an abstract class NumericIntegration that can hold some common methods, such as validate() and sort(), as well as common constants (X =0, Y=1 for indexing). Then, the classes for the techniques themselves can just extend the NumericalIntegration class and simply provide a solve() method.

Let me know if there are any problems with this approach.

**Comment by Beakerboy** [comment]
Are the methods going to work on arrays of data, or will they work on callables as well? I have some traits in the regression area that I'm considering changing into classes. My idea was to come up with a generic structure which would allow a mathmatical function to be used more broadly. In my case, using it in a linear regression, or even a non-linear least squares regression.

**Comment by jakobsandberg** [comment]
I was actually going to include callables next! Although I'm not sure of the best way to support both callables and arrays of data (in terms of a logical representation).

I could include an additional method

```toPoint(callable $function, $start, $end, $n)```

that evaluates the callable $function at $n points between (and including) $start and $end, and simply returns an array of data that could work in the present model. Thus, the two different types of implementations would work as follows:

```
// Existing implementation with array input
$points = [[0, 1], [1, 4], [2, 9], [3, 16]];
$∫f⟮x⟯dx = TrapezoidalRule::solve($points);

// Potentially new implementation with callable input
$f⟮x⟯ = function($x) {
    return $x**4 + 8 * $x**3 - 13 * $x**2 - 92 * $x + 96;
};
$min = 0;
$max = 10;
$n = 10;
$∫f⟮x⟯dx = TrapezoidalRule::solve(toPoints(f⟮x⟯, $min, $max, $n));
```

Alternatively, we can remove the input type hinting of solve() and allow both callable and array inputs. From there, we can include a method to determine whether the input is a callable or an array (or neither). OR we could create two distinct functions, one that takes a callable input, and another that takes an array input.

There's probably other approaches as well. Let me know what you think.

**Comment by jakobsandberg** [comment]
I definitely think it would be a good idea to come up with a generic structure. This would also reflect better OOP design patterns.

**Comment by markrogoyski** [comment]
If you use a single function with a generic input ...splat parameter or something, you can check in the function for what type it is.
For example, 
if ($func instanceof Closure) 
or
if (is_callable($func))
, etc.
http://php.net/manual/en/internals2.opcodes.instanceof.php
http://php.net/manual/en/function.is-callable.php

**Comment by jakobsandberg** [comment]
@markrogoyski that seems like a solid approach! Normally I would want to separate a method into two if it takes two very different types of inputs, but because both inputs will lead to the same result (and only include one intermediate step) this seems to be a good way to go.

**Comment by jakobsandberg** [comment]
So we could do something like this:

```
public station function solve($source, $args = []) {
    $callable = is_callable($func);

    if ($callable) {
        $function = $source;
        $start = $args[0];
        $end = $args[1];
        $n = $args[2];
        $points = self::toPoints($function, $min, $max, $n);
    } else {
        $points = $source;
    }
}
```

And the $args variable would just be empty when the original input is an array.
