### ISSUE TITLE
Hypergeometric Functions

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#109]
In case you didn't specifically notice, I have Hypergeometric functions in the code base now, so if either of you are interested in Bessel Functions or other stuff in the family, have at it.

**Comment by markrogoyski** [comment]
Great addition. Thanks for implementing.

Do you mind adding some documentation on the input parameters for those functions?
Thanks!

**Comment by Beakerboy** [comment]
I added some documentation. minimal, but there. I can't say i really know what these functions "do", or what the parameters "mean". I just know they work right...and I need them for the Non-central T distribution...which I need for tolerance intervals.

**Comment by markrogoyski** [comment]
Thanks for adding the comments. I normally add documentation for stuff, but for those functions I wasn't quite sure.
Btw, it still looks like one line has some characters that don't display.
Line 660:
     *                   n   (a + n - 1) * z
     *   ₁F₁ ₙ = ₁F₁ ₙ₋₁ + ∏  -----------------  = ₁F₁n₋₁ + ∏n
     *                   1   (b + n - 1) * n

Also it looks like the indention or spacing isn't quite right. I fixed the one above it by referencing the formula in Wikipedia, but for this one I wasn't sure what it was supposed to be.
