### ISSUE TITLE
Namespace for Root Finding

### ISSUE THREAD

**Issue by markrogoyski** [markrogoyski/math-php#110]
I was thinking of creating a new namespace within NumericalAnalysis for RootFinding (or RootApproximation). NewtonsMethod would go in there, and if any others got implemented, like Secant method or Muller's method or whatever, they would join Newton.

Does NumericalAnalysis\RootFinding sound appropriate? Ideas for a better name?

**Comment by jakobsandberg** [comment]
I don't see any major problem with it. Maybe "Solve" or "Approximate" would be a more mathematical way of expressing "Find".

Other options:
- EquationRoots
- EquationSolver

**Comment by markrogoyski** [comment]
The Wikipedia articles all seem to use "Root Finding"
https://en.wikipedia.org/wiki/Root-finding_algorithm
https://en.wikipedia.org/wiki/Category:Root-finding_algorithms

First line of Newton's Method Wikipedia article:
_This article is about Newton's method for **finding roots**._

First line of Secant Method Wikipedia article:
_In numerical analysis, the secant method is a **root-finding** algorithm ..._

This seems like common usage (at least on Wikipedia), so I'll probably just stick with RootFinding.
Thanks for the suggestions.
