### ISSUE TITLE
Applied Math Topics?

### ISSUE THREAD

**Issue by jakobsandberg** [markrogoyski/math-php#126]
What do you all think about extending to topics such as Financial Mathematics? As I'm working on the Numerical Analysis topics, I keep thinking how these techniques could easily be applied to topics such as Financial Engineering and Financial Economics.

Or, are we trying to keep this strictly mathematical?

**Comment by markrogoyski** [comment]
I think it is a great idea. If it involves numbers and operations on them, it's math.

I was planning on doing some basic financial stuff like compounding interest and stuff. I've already implemented moving averages which are used a lot in stock trading.
It sounds like you might be talking about more advanced applied stuff like what is described here:
https://en.wikipedia.org/wiki/Mathematical_finance
I think all of that would be a great to have.
