### ISSUE TITLE
Exception Classes

### ISSUE THREAD

**Issue by wizard97** [markrogoyski/math-php#142]
I think it would be nice to add custom Exception classes. Rather than just throw a generic \Exception, it would be nice to be able to catch Exceptions for certain errors.

**Comment by markrogoyski** [comment]
Yes. I was thinking things like ParameterOutOfBoundsException etc. would be useful.

The first step would be to come up with the list of common Exceptions, and then figure out where the Exception classes will live in the directory structure.

**Comment by markrogoyski** [comment]
The Standard PHP Library has some build-in custom exception classes that could probably be used first before creating any custom exceptions.

For example:
 * OutOfBoundsException
 * OutOfRangeException
 * InvalidArgumentException
 * RangeException
 * UnexpectedValueException
 * etc.

http://php.net/manual/en/spl.exceptions.php

**Comment by wizard97** [comment]
I think subclassing these would only make sense if all these Exceptions and potential subclasses of them would cover all the possible error conditions. Perhaps you might make something along the lines of a MathException base class, and derive all your custom Exceptions from that.

**Comment by markrogoyski** [comment]
The most commons exceptions involve parameters being out of bounds or incorrect in some other way. In the Matrix class, it is common to throw exceptions when expecting a Square matrix, or if some row/column doesn't exist.

I'll give it some thought about how to generalize these to a few custom exceptions. It will probably go in namespace: `\Math\Exception\`

**Comment by markrogoyski** [comment]
It seems like both routes have their benefits.

A custom MathPHP Exception class for all the custom exceptions to inherit from would allow the user to distinguish all exceptions that were MathPHP related, as apposed to some other library, or PHP exceptions, etc.

Extending the SPL exceptions on the other hand could make use of the common existing exception types that would seem to apply to what we are doing: OutOfBounds, Range, etc.

Do you have a strong opinion for either route?

**Comment by wizard97** [comment]
Alternatively, if you are willing to derive all Exception from a base `MathException` you could do something like this:

`MathException` (Derived from `\Exception`)
- `LinAlgException`
    * `MatrixException`
       - `NonSquareMatrixException`
       - `UnequalMatrixSizeException`
        - `EmptyMatrixException`
       -  etc...
    * `FunctionException`
       - etc...
- etc...

The advantage of this, is it would allow you to catch MathExceptions, allowing you to catch all Exceptions raised by this library.

**Comment by markrogoyski** [comment]
Yeah. I think having the option to distinguish a MathPHP exception from other exceptions in your code would be a benefit. Maybe a math error is something you could recover from gracefully and not take down your entire script, like an endpoint not existing exception or something.

I think this is the way to go. I would want to take it slow though and survey what kinds of exceptions we have and try to categorize them and generalize them so we don't end up with 100 different exceptions when in reality there are only like 10 different error scenarios really happening.

**Comment by wizard97** [comment]
> A custom MathPHP Exception class for all the custom exceptions to inherit from would allow the user to distinguish all exceptions that were MathPHP related, as apposed to some other library, or PHP exceptions, etc.

This was exactly the point I made with my previous comment, before I even saw yours. :)

> Extending the SPL exceptions on the other hand could make use of the common existing exception types that would seem to apply to what we are doing: OutOfBounds, Range, etc.

Yeah I agree, the advantage of this is it fits better with polymorphism and abstracts the actual type the operation is being performed on. Imagine doing multiplication between two abstract types `$a` and `$b`:
```
try {
    $c = $a * $b;
} catch (InvalidArgumentException $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

What is boils down to, is deriving from standard PHP Exceptions allows better compatibility with other libraries and working with abstract types.

>  I think this is the way to go. I would want to take it slow though and survey what kinds of exceptions we have and try to categorize them and generalize them so we don't end up with 100 different 

Agreed, the Excpetion hierarchy should be well thought about before actually implementing it.

**Comment by wizard97** [comment]
Actually I realize now PHP does not support operator overloading (/, *, -, +, etc...), so it makes my previous point about working with abstract types less relevant. As opposed to something like Python where duck typing is common practice.

**Comment by markrogoyski** [comment]
I think implementing these custom exceptions would cover most of the exceptions that currently exist:

* \MathPHP\Exception\OutOfBoudsException
* \MathPHP\Exception\BadDataException
* \MathPHP\Exception\BadParameterException
* \MathPHP\Exception\IncorrectTypeException
* \MathPHP\Exception\MatrixException

And they could all inherit from a generic \MathPHP\Exception\MathException which could be used for anything that doesn't have a more specific custom exception.

Thoughts?

**Comment by wizard97** [comment]
Sounds good to me!

It is easy to add additional Exceptions if you find you missed any, since they all inherit from your base Exception. 

Since this isn't just a quick fix, perhaps you should branch develop into a new Exception branch, and merge back once the whole custom Exception system is done.

**Comment by markrogoyski** [comment]
I added a new branch **exception** that is refactored from develop with custom MathPHP exception classes, and all previous exceptions have been converted to one of the custom exceptions.

**Comment by markrogoyski** [comment]
This is now in the latest release (v0.13.0).
