### ISSUE TITLE
Using static vs non-static methods for the Polynomial class

### ISSUE THREAD

**Issue by jakobsandberg** [markrogoyski/math-php#148]
What are your thoughts on using static methods for things like `add()` and `multiply()` in the polynomial class? The current procedure utilizes instantiated objects and then adds a second object as an argument:

```
$polynomial = new Polynomial([1,2,3]);
$secondPolynomial = new Polynomial([3,2,1]);
$sum = $polynomial->add($secondPolynomial);
```

I think it would feel more natural to use static methods, because addition and multiplication aren't operations that depend on knowledge of an existing object. For example:

```
$sum = Polynomial::sum($polynomial, $secondPolynomial);
$product = Polynomial::multiply($polynomial, $secondPolynomial);
```

I feel this notation is more natural for the addition and multiplication which operate on two values.

In the case of `differentiate()` and `integrate()`, I feel it is fine to keep those as non-static because they are operators and only act on one object.

**Comment by markrogoyski** [comment]
Do you envision the Polynomial class being used by users, or is it mostly just for internal operations of other functions that are exposed to the user?

If it is intended as internal only, then I can see the benefit of reducing code complexity to get an add or multiply operation down to one line. It comes at the expense increasing the cognitive complexity of the Polynomial API, having to remember (or look up) which methods or object or static methods. If it is only internal, then it's not a big deal. So go for it if you think the benefit will result in clearer, more natural code.

If the Polynomial class is intended to be exposed to and used by users, however, then I would stress the importance of a consistent API that is easy to use. If some methods are object methods and some are static class methods within the same class, it can become confusing to the user who just wants to add and differentiate polynomials. A developer familiar with the project knows where to look to see how something works; a user may just get frustrated that the API is inconsistent and give up.

It's unfortunate that PHP doesn't have operator overloading like C++. Then the choice would be obvious:
`$sum = $polynomial1 + $polynomial2;`

**Comment by markrogoyski** [comment]
Another option, is if you envision other types of models, like non polynomials type equations, being added to polynomials or other types of equations, then maybe it would make sense to generalize the concept of adding and multiplying equations. Those methods (static) could take two polynomials, or two non polynomials, or one of each, and add them and return the appropriate object.

Then the Polynomial would be all object methods, and the generalized function arithmetic class that now takes polynomials and whatever else, could be static and do the right thing depending on what the input is.

Maybe that is a bit over engineering an answer in search of a problem. Just an idea. Not sure if it is a good one.

**Comment by jakobsandberg** [comment]
I definitely see it being used more for internal operations, in particular, because many of the numerical methods I've built depend on polynomials. Although I see no reason users can't utilize them as well.

With respect to your point on keeping a consistent API, I do see how it can be confusing to have a class with both object methods and static methods. For now, I think it's best to keep it as strictly object methods.

It would definitely be handy to have operator overloading or some magic methods like `__add` and `__multiply`. Hopefully we'll see something like that in PHP 7.X.
