### ISSUE TITLE
Lanczos Approximation error

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#152]
I was running a unit test on a new distribution, which, down the rabbit hole, calls the gamma function with the value 86.5. The library currently says gamma(86.5) = INF. Excel returns 2.608E129, large, but still something that should be able to be returned. I see that you use the values of N=9 and g=7 for the Lanczos parameters. Where do these come from? Boost recommends N=6 and g=1.428456135094165802001953125  for 24 bit significance.

http://www.boost.org/doc/libs/1_61_0/libs/math/doc/html/math_toolkit/lanczos.html

**Comment by markrogoyski** [comment]
This is what I referenced: http://mrob.com/pub/ries/lanczos-gamma.html

Don't hesitate to improve it with a better method.

**Comment by Beakerboy** [comment]
Both that site and boost have a description of how to generate the factors with some matrix algebra. I think I'll Putz around and implement this procedure in the support functions. This way it's documented how they are generated, and if somebody wanted to use different values for g and N there would be a way to produce them. However on initial glance the matrices that the two sites use are slightly different. I'm guessing boost combines two of them into one matrix.

**Comment by Beakerboy** [comment]
Turns out it's not the Lanczos approximation, it's in the half integer case. I changed the calculation to use the double factorial instead of the factorial, and that should fix this.
