### ISSUE TITLE
Dealing with \INF

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#156]
It's nice that PHP supports the idea of infinity. However, in many cases in this library it means a variable has overflowed. I was thinking it would make sense for functions to do something like:

```
$return = [some final calulation];
if (is_infinity($return)) {
    //throw overflow exception
}
return $return;
```

For coverage, we would need to figure out how to overflow everything though. Any ideas on a good way to deal with this?

**Comment by markrogoyski** [comment]
I'm not sure I follow why you would consider infinity an error. PHP supports some really large numbers, so if it thinks something is infinity, it is usually very large.

For example, on my machine:
`print(PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX * PHP_INT_MAX . "\n");`
That prints out: 4.1094811730847E+208

That is very large without being considered infinity.

To get PHP to return infinity, I have to do something like this:
`print(PHP_INT_MAX ** PHP_INT_MAX . "\n");`

Do you have some examples of where you are getting infinity and that is clearly not appropriate?

**Comment by Beakerboy** [comment]
the regularizedIncompleteBeta was dividing a value by beta, which is a ratio (gamma(x)*gamma(y)/gamma(x+y)). Before I changed the Gamma function to use the double factorial, it was returning infinity due to calling our factorial function with x+y, making beta zero, and throwing a divide by zero in regularizedIncompleteBeta.

**Comment by Beakerboy** [comment]
You can close this.  In the end, some of the special functions might have to have their algorithms optimized when working on some extremes. The gamma function is often calculated as the log of gamma to minimize the likelihood of blowing up.

**Comment by markrogoyski** [comment]
If there are specific improvements that can be made to the gamma function, regularizedIncompleteBeta, or any other special functions, feel free to create an issue with the specific improvement and strategy to achieve it. Thanks.
