### ISSUE TITLE
Regularized incomplete beta function and real numbers

### ISSUE THREAD

**Issue by markrogoyski** [markrogoyski/math-php#16]
The regularized incomplete beta function as is only works for integers and half integers. Is this correct? Is this going to be an issue. Does it need to work for all real numbers? Is there an algorithm for them?

**Comment by Beakerboy** [comment]
The function is defined for a real numbers, but this algorithm only works for integer multiples of .5.

Implementing regularized incomplete beta for the rest will require a continuous fraction. I'll do it today.

**Comment by Beakerboy** [comment]
This is also in the pending pull request.

**Comment by markrogoyski** [comment]
Thanks for updating the function.

I added many unit tests and it looks good for most calculations. However, I found a case where the calculations don't match the online calculator I was using to create the unit test data.
When $a is a half integer (#.5) and $b is an integer, the result doesn't seem to match the online calculators.
For example:
$x = 0.55, $a = 2.5, $b = 2
This online calculator gives this result: 0.47672251 (http://www.analyticscalculators.com/calculator.aspx?id=37)

However, our function gives this result: 0.35452425122782244

Can you check this case?
Thanks.

**Comment by Beakerboy** [comment]
Will do. I was using the[http://functions.wolfram.com/webMathematica/FunctionEvaluation.jsp?name=BetaRegularized](Mathworld site).

**Comment by Beakerboy** [comment]
Those recursive functions in the top 'exact' part of the method are likely extensions of the translation functions in the bottom. I bet if I pull out my algebra skill, I can double check the for loop to make sure it's correct.

**Comment by Beakerboy** [comment]
I added a pull request to fix this.

**Comment by markrogoyski** [comment]
Merged pull request and added new unit tests. All tests pass.
