### ISSUE TITLE
Vector to share interface with Matrix for common operations

### ISSUE THREAD

**Issue by markrogoyski** [markrogoyski/math-php#174]
User @aboks suggested the idea that the Vector and Matrix classes could share a common interface for certain matrix operations. This would allow Vectors to make use of certain Matrix operations that they cannot currently use.

This would utilize the fact that Vectors can be thought of as 1 x n Matrices. Therefore, if a Matrix operation works on a non square 1 x n matrix, the Vector can perform the same operation.

Need to consider what the implications are for this.

**Comment by Beakerboy** [comment]
I've often thought about this. The best philosophical argument I've heard is, a vector and a matrix are different things. However, a 1xn matrix can be represented by a vector. Similarly, a tensor is different from a matrix, but certain types of tensors can be represented by a matrix.

**Comment by markrogoyski** [comment]
It's easier to think of them as being different...but related. If someone wants to use a Vector like a Matrix, the Vector class has asRowMatrix() and asColumnMatrix() to convert it a matrix. Perhaps that is good enough.

Closing for now as not going to implement at this time.
