### ISSUE TITLE
P1 and P2 for tTestTwoSample() are NAN

### ISSUE THREAD

**Issue by pbogut** [markrogoyski/math-php#175]
I have this two sets of data where I was trying to get P value, unfortunately, `Significance::tTestTwoSample()` returns `NAN` as `p1` and `p2` value.

Here's the data: [google-doc](https://docs.google.com/spreadsheets/d/1UKKI8dVfc-cUWAqIc0zgltp0ljvA6MwuomWOADZa8H4/edit?usp=sharing)

Google Docs `TTEST` function is calculating P Value as `0.401338048`

Code to reproduce:
```php
    $result = Significance::tTestTwoSample(
	150.0648965,
	126.7361145,
	68,
	292,
	233.8012747,
	199.3031358
    );
```

results in:
```php
    [
     "t" => 0.76094082649196,
     "p1" => NAN,
     "p2" => NAN,
    ]
```

Is that an error, or I've done something wrong?

Edit:
Here's some other tool that can calculate the data: [epitools](http://epitools.ausvet.com.au/content.php?page=2-sample-t-test&mean1=150.06&mean2=126.73&sd1=233.80&sd2=199.30&n1=68&n2=292&Conf=0.05&Digits=3&tails=2&samples=0). T value is different, P value is the same as one in google docs.

**Comment by Beakerboy** [comment]
Without diving into the code, I'm guessing it's due to the regularized incomplete beta function blowing up due to high degrees of freedom. When the degrees of freedom are this large the distributions are so close to normal that the algorithm takes a long time to converge.

**Comment by markrogoyski** [comment]
Hi @pbogut,
Thanks for posting this issue. I was able to reproduce it.

@Beakerboy: Yeah, it looks like the regularized incomplete beta function is returning NAN with the input of a test statistic t of 0.76094082649196 as x, and degrees of freedom 358 as shape parameter a and 1/2 for shape parameter b.

**Comment by markrogoyski** [comment]
It looks like the regularized incomplete beta function calls the beta function, and the beta function calls the gamma function, and when the gamma function gets an input of like 179 in this case it returns infinity. Then the beta function seems like it has an INF / INF situation due to the large input which produces the NAN that makes back through the parent beta function.

**Comment by markrogoyski** [comment]
On this Web page calculator for the gamma function: ([http://keisan.casio.com/exec/system/1180573444](http://keisan.casio.com/exec/system/1180573444)),
given an input of 179, it produces the result of: 6.23513539724190874168E+324, which for all intents and purposes, is infinity, so the gamma function returning infinity is not wrong, however, the beta function then has an INF / INF situation which is going to produce the NAN.

Thoughts?

**Comment by markrogoyski** [comment]
Also, @pbogut, the t test is usually used when the sample size is small, say n < 30. Since you have a large sample size, a z test might be more appropriate, as @Beakerboy had mentioned.

**Comment by pbogut** [comment]
@Beakerboy, @markrogoyski 
Thanks for the suggestion about z-test. I'm not a statistician, I've been told to use t-test.
 I've tried to check z test, but I don't think this library has two sample z test implemented (at least I can't find it). Is that correct?

**Comment by markrogoyski** [comment]
@pbogut,

I've added a specific two-sample z test. You use it exactly the same was as the two-sample t test.

```php
// Z test - Two samples (z and p values)
$μ₁ = 27;   // Sample mean of population 1
$μ₂ = 33;   // Sample mean of population 2
$n₁ = 75;   // Sample size of population 1
$n₂ = 50;   // Sample size of population 2
$σ₁ = 14.1; // Standard deviation of sample mean 1
$σ₂ = 9.5;  // Standard deviation of sample mean 2
$z  = Significance::zTestTwoSample($μ₁, $μ₂, $n₁, $n₂, $σ₁, $σ₂);
/* [
  'z'  => -2.36868418147285,  // z score
  'p1' => 0.00893,            // one-tailed p value
  'p2' => 0.0179,             // two-tailed p value
] */
```

This is available in the latest release, v0.17.0.

Keep in mind that if your sample size is > 30, you generally will use the z test, which is now available.

Thanks for posting this issue which brought about this new feature.

**Comment by pbogut** [comment]
@markrogoyski 
Thank you very much for implementing this. I've tried to use it and it looks very good.

Thanks for doing a great job with this library.

**Comment by Beakerboy** [comment]
Should this be closed?
