### ISSUE TITLE
Remove Standard Tables?

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#18]
I'm guessing these are unnecessary if we are able to calculate everything, and to greater precision, correct?

**Comment by markrogoyski** [comment]
Most statistics textbooks provide the standard normal tables as a reference, so I'd prefer to keep providing them, even if they aren't used in any automated calculations. Just a nice thing to have. But yeah, in any calculation, if you can do the calculation automatically with greater precision, then that is ideal.
