### ISSUE TITLE
Population/sample variance...extending

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#19]
You have functions for population variance and sample variance. I was thinking it might be worthwhile combining these into a common function.

    function SumOfSquares(array $numbers){
         if (empty($numbers)) {
            return null;
        }
        $μ         = Average::mean($numbers);
        $∑⟮xᵢ − μ⟯² = array_sum(array_map(
            function ($xᵢ) use ($μ) {
                return pow(($xᵢ - $μ), 2);
            },
            $numbers
        ));
        return  $∑⟮xᵢ − μ⟯²;
    }

    function variance($numbers, $degrees_of_freedom){
        self::SumOfSquares($numbers) / $degrees_of_freedom;
    }

    public static function populationVariance(array $numbers)
    {
        return self::variance($numbers, count($numbers));
    }

     public static function sampleVariance(array $numbers)
    {
         return self::variance($numbers, count($numbers) - 1);
    }
The reason is, there are many cases where the degrees of freedom is not just $n or $n - 1. Also, the sumOfSquares function itself is used in so many situations.

**Comment by markrogoyski** [comment]
I added RandomVariable::sumOfSquaresDeviations and added a new Descriptive::variance method like you describe that allows custom d.f, and population/sample variance now use variance. Added new unit tests.
