### ISSUE TITLE
Quadratic Equation and imaginary results

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#192]
I have not tested, but I did not see anything obvious in the new quadratic function, and dealing with imaginary numbers. Does it need to throw an exception? Ideally, this library would have an ImaginaryNumber class that could be returned in these cases.

**Comment by markrogoyski** [comment]
Right now if the discriminant is negative it will result in NAN when it tries to take its square root. Considering there currently isn't a concept of Imaginary/Complex numbers in the library, do you think it makes more sense to throw an exception or continue to return NAN when the discriminant is negative?

Ideally there will eventually be some sort of imaginary/complex number class integrated where appropriate, but that is future talk, and right now this function exists.

**Comment by Beakerboy** [comment]
It doesn't matter to me what it does, but there should be a test and it should be written in the documentation.

**Comment by Beakerboy** [comment]
Also, would it make sense to add:
`if(a==0) return [-c/b];`

**Comment by Beakerboy** [comment]
Also,
 `   public static function cubic_root($a, $b, $c, $d): array
    {
        if ($a !== 1) {
            $b = $b / $a;
            $c = $c / $a;
            $d = $d / $a;
        }
        $Q = (3 * $c - $b ** 2) / 9;
        $R = (9 * $b * $c - 27 * $d - 2 * $b ** 3) / 54;
        $D = $Q ** 3 + $R ** 2;
        $S = ($R + sqrt($D)) ** (1/3);
        $T = ($R - sqrt($D)) ** (1/3);
        $x = [];
        $x[] = $S + $T - $b / 3;
        if ($S == $T) {
            // No Complex Roots
            $i = 0;
            $x[] = -$b / 3 - ($S + $T) / 2 + $i * sqrt(3) * ($S - $T) / 2;
            $x[] = -$b / 3 - ($S + $T) / 2 - $i * sqrt(3) * ($S - $T) / 2;
        }        
    }`

**Comment by markrogoyski** [comment]
Thanks for the feedback. You bring up good points that behavior should be documented. And I did not cover the edge case of a = 0 where the formula is not quadratic.

I've implemented the edge cases, and documented the behavior in the function's docBlock comments and as new unit tests describing the behavior.

Changes are in the develop branch: https://github.com/markrogoyski/math-php/commit/44750bbce9507b61368feabddedd497ecf1d64b5

**Comment by markrogoyski** [comment]
Regarding the cubic root function you provided, initially I thought you were talking about cube roots, as in ³√x, which is strange since you can just do `pow($x, 1/3)`, but then I saw the four input parameters and realized what you are doing. =)

I think perhaps calling it cubicEquation() might avoid ambiguity in meaning.

As always, thanks again for the feedback and suggestions.

**Comment by markrogoyski** [comment]
@Beakerboy 
I added cubic equation. It was a little more involved than what you proposed above. Please check it out.

Cubic equation in develop branch: https://github.com/markrogoyski/math-php/commit/5d7a9a830ffad596b4dcb3f928f88a5bb9956dcf
Cubic equation unit tests in develop branch: https://github.com/markrogoyski/math-php/commit/82660130fb4d1e8e06bd341ac36be91ac4d56050
