### ISSUE TITLE
basic complex algebra addition for matrices and vectors

### ISSUE THREAD

**Issue by TheFausap** [markrogoyski/math-php#193]
Hello,
is there any plan to add a basic complex numbers manipulation, for matrices and vectors ?

thanks,
Fausto

**Comment by Beakerboy** [comment]
Describe what you mean by "basic complex". There are element-wise arithmetic operations in the Vector and Matrix classes.

**Comment by markrogoyski** [comment]
Hi. Thanks for your interest in Math PHP!

I would like to eventually add imaginary/complex number support.

@Beakerboy, I have thought about this, and I'm not sure from a design standpoint how best to implement complex numbers. An actual complex number class is easy. The problem I see is how to integrate that into the rest of the library.

PHP unfortunately does not have operator overloading like in C++. Therefore any function that could possibly take in real numbers and complex numbers; or during calculations be dealing with real or complex numbers, the conditional logic could get very messy very quickly.

I'm not sure what an optimal design looks like at this point. Or perhaps I'm thinking about this the wrong way. What are you thoughts on how you would design (or retrofit) functions that could have a mix of real and complex numbers?

**Comment by TheFausap** [comment]
@Beakerboy, yes... I mean complex algebra. I tried to use a complex package (https://github.com/suopte/ferrari-php/blob/master/complex.php), but the main problem, as noticed by @markrogoyski, is there's no operator overloading. I tried to change the standard multiplication with the custom complex multiplication, but I got errors.
I modified Multi.php, to handle the complex numbers (defined in the class above):

`$products[$i] = $products[$i]->mul($arrays[$j][$i]); `

but I have this error:
PHP Fatal error:  Uncaught Error: Call to a member function mul() on integer in /home/vandine/PHP-QC/vendor/markrogoyski/math-php/src/Functions/Map/Multi.php:88
Stack trace:
#0 /home/vandine/PHP-QC/vendor/markrogoyski/math-php/src/LinearAlgebra/Matrix.php(997): MathPHP\Functions\Map\Multi::multiply(Array, Array)
#1 /home/vandine/PHP-QC/ql.php(47): MathPHP\LinearAlgebra\Matrix->vectorMultiply(Array)
#2 {main}
  thrown in /home/vandine/PHP-QC/vendor/markrogoyski/math-php/src/Functions/Map/Multi.php on line 88

the code I'm using is 

```
require_once __DIR__ . '/vendor/autoload.php';
require_once 'complex.php';
use MathPHP\LinearAlgebra\Matrix;
use MathPHP\LinearAlgebra\Vector;

$k0 = new Vector([0.0, 1.0]);
$I = complex(0.0,1.0);
$MI = complex(0.0,-1.0);
$Y = new Matrix(
        [
                [0.0,  $I],
                [$MI, 0.0]
        ]
);

$prod1 = $Y->vectorMultiply($k0);
echo "Vector: " . $prod1 . "\n";
```
(the complex class, is able to handle multiplication between complex-complex and complex-real).

In the code, there're no integer values, so why I got that error?

thanks,
Fausto

**Comment by Beakerboy** [comment]
I'd say a ComplexNumber class should contain add(), subtract(), multiply(), and divide(). these functions should be able to operate on either native PHP numeric data types or ComplexNumber objects. Some algebra would be a little obtuse, for example, If someone wanted to perform 42 - (6+2i), they would have to do:
`$com_num = new ComplexNumber(2,2);
$result = $com_num->multiply(-1)->sum(6);
`

**Comment by Beakerboy** [comment]
From a library-design standpoint, I'd say we add complex number support when it's requested before doing something extreme, like defining an add($a, $b) function that is used universally throughout the library. We could try it for this case though. Instead of defining a ComplexNumber::add() we could just define MathPHP::add() which will work on both complex and real numbers.

**Comment by TheFausap** [comment]
@Beakerboy for this reason I tought modifying Multi.php could be enough. 
With the original code, I have an error about *-operation and object teComplex, as you described.

It seems mul() get an integer somewhere, and for this reason I got that error.

By the way you Matrix class, can print (at least) the a matrix with complex values inside :) 

But, you need to modify a little the complex.php: toString -> __toString.

**Comment by Beakerboy** [comment]
@TheFausap I've just added a pull request for a complex number class. If you would like to test this out in a custom ComplexVector or some other object, go ahead and let us know how it works.

**Comment by Beakerboy** [comment]
I was looking at my Eigenvalue class, getting it ready to extend it to 4x4 matricies, and it is getting quite complex. However, I think I can simplify it by adding another class to the Number namespace. If I create a Polynomial class, and use this in a matrix, I can easily produce the polynomial of λ, and push that to the root-finding function for any. Where this issue helps with THIS issue, is I can mandate that any object in this  ExoticMatrix (or whatever I call it) must implement an Interface, to ensure that they can perform all the basic algebra functions. Then this ExoticMatrix can work on more interesting data structures.

Where this applies into THIS issue, is this will then allow for matrix math of complex numbers.

**Comment by TheFausap** [comment]
@Beakerboy Sorry for the delay, but I didn't read the previous email alert. I tried it with vector, but I have a problem, maybe with get method:

```
$k0 = new Vector([1.0, 0.0]);
$I = new Complex(0.0,1.0);
$MI = new Complex(0.0,-1.0);

$Y = new Matrix(
    [
        [0.0,  $I],
        [$MI, 0.0]
    ]
);

$prod1 = $Y->vectorMultiply($k0);

printq($prod1,0);

```
where the function printq is:

```
function printq(Vector $v, int $width)
{
    $len = $v->getN();

    $noexpand = false;

    if ($width == 0) {
        $noexpand = true;
    }

    if ($noexpand) {
        for ($i = 0; $i < $len; $i++) {
            if ($v->get($i) <> 0) {
                echo $v->get($i) . "|" . decbin($i) . "> ";
            }
        }
    }

    echo "\n";
}
```
I suppose there's a problem with echoing a complex number, because the result is 

1|1>

and it shoul be

-i|1>

What do you think ? 

thanks
Fausto

**Comment by Beakerboy** [comment]
@TheFausap these changes have not been implemented yet, so the vectormultiply method is still undefined for complex numbers in this class.

**Comment by markrogoyski** [comment]
@Beakerboy 
There is a ```MathPHP\Functions\Polynomial``` class. Would you add on to that, or are you considering something completely different for the Number namespace? Namespaces enable you to have multiple classes with the same name, which is great if you have the same thing in different contexts. However, it can also be confusing if you have multiple classes with the same name, especially if there is overlap in functionality.

So check out what is in ```Functions\Polynomial``` first before you potentially reimplement something.

**Comment by TheFausap** [comment]
@Beakerboy I tried define a vector and matrix with complex numbers, and printing them: this works.
All the operation with matrices or vectors, if I understand well, at the moment are not implemented yet.
Correct ?

**Comment by Beakerboy** [comment]
@markrogoyski That looks exactly like what I need, thanks.

@thefausap a user can currently populate a matrix with any data type. There is no check on that in the constructor. However, all of the operations are defined using traditional arithmatic operators, like +-*/. The objects, like our Complex object have add(), and subtract() instead. Therefor, we will need to make another Mateox class that does all the same stuff, but uses function calls instead of operators.

**Comment by TheFausap** [comment]
@Beakerboy yeah, I see. But it should be possible also mix the types, I mean I could define a matrix in this way:

```
$Y = new Matrix(
    [
        [0.0,  $I],
        [$MI, 0.0]
    ]
);
```
and be able to perform a scalar (element-wise) multiplication (for example) with a real number.

Otherwise I should define everything as complex number, but this could be excessive.

**Comment by Beakerboy** [comment]
The Complex class is smart enough to know how to handle operations involving real numbers. However, if $i is an integer, and $c is a Complex object, $c->add($i) is defined, but $i->add($c) is not. The new ObjectMatrix would have to check the data type. If it is a native numeric then is would have to use the commutive rule to switch the order of operation, or, if both are real, to use the native algebraic operators. I think the best route would be to specify what set of numbers are used, and all elements would be that data type. That way there are no mixed typing issues.

**Comment by Beakerboy** [comment]
I think this can be closed. As long as a user creates an ObjectMatrix with Complex objects, they can do basic matrix manipulations with those objects, and Complex Numbers are an Object in this library. Other more complicated matrix operations will have to be added to the ObjectMatrix as requested. Since mathematical operations will not work on Objects, all +, *, and - have to be replaced with Object->add(), etc. Also, division is not supported by all objects, so some algorithms would need be be changed (Like I did with the determinant), or another ObjectMatrix will have to be made for objects which CAN be divided.

**Comment by markrogoyski** [comment]
Closing this issue. Please try out ObjectMatrix for basic complex arithmetic. If any other operations are required, please open a new issue with the requested functionality.

Thanks.
