### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by landers2014** [markrogoyski/math-php#198]
file : src/Statistics/Regression/Methods/LeastSquares.php 
function : meanSquareResidual
line : 283 ($MSE = $SSₑ / $ν;)

**Comment by Beakerboy** [comment]
What does your data look like? Are you fitting a line to only two data points? The degrees of freedom, $ν, is only zero when there is enough data to exactly fit the line or polynomial **without** least-squares (2 point for a line, three for a second order polynomial, etc). 

Despite that, you are correct that the class should do something for these edge cases, by either returning 0 for MSE, or throwing an exception that there is not enough data to use the class.

**Comment by markrogoyski** [comment]
@Beakerboy 
The degrees of freedom ν is computed in LeastSquares->leastSquares method. Do you think it makes sense to throw a BadDataException here if ν is 0?

**Comment by Beakerboy** [comment]
Yes, that would probably be the best solution.

**Comment by markrogoyski** [comment]
This has been addressed in the latest release, v0.26.0. Thank you for reporting the issue.
