### ISSUE TITLE
PSR-2 and LICENSE

### ISSUE THREAD

**Issue by dantleech** [markrogoyski/math-php#2]
Would be a nice touch to adopt the PSR-2 [coding guidelines](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) and add a LICENSE.

**Comment by markrogoyski** [comment]
Hi,

I'll review the PSR-2 standards and start conforming to that. It seems strange that the PSR-2 standard uses both K&R and Allman-style curly brace indentation styles depending on whether it is a control structure or class/method. I can get used to it though.

I haven't put much thought into a license. I'll probably go with MIT or something.

Thanks for the input.
Mark

**Comment by dantleech** [comment]
You might be interested in [style ci](https://styleci.io) which provides continuous integration for code style, and also  a diff / PR for fixing the code style (i.e. it can convert the code to PSR-2).

If you want any help with that or setting up [travis CI](https://travis-ci.org) let me know and I could make a PR.

**Comment by markrogoyski** [comment]
All code now conforms to PSR-2 (Confirmed using PHP CodeSniffer). An MIT license has also been added.
