### ISSUE TITLE
add gamma, dirichlet, and categorical distributions

### ISSUE THREAD

**Issue by happyjack27** [markrogoyski/math-php#209]
categorical is rather similiar to multinomial.

dirichlet is an extension of the beta distribution, for a multinomial rather than just binomial posterior.  it's a rather important distribution.

as is gamma - it's expected arrival counts within a time span, for a poisson process.  it's the conjugate prior to a lot of distributions

**Comment by markrogoyski** [comment]
Thank you for the feature requests. These distributions have been added.
