### ISSUE TITLE
Should we add a "Failure to converge" exception?

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#216]
I'm working on replacing the core of the Continuous::inverse() method with the NewtonsMethod::solve() method, since that's basically what it's doing. However, it seems to always be returning NAN. This method returns NAN in two instances, where the slope is small enough to be considered zero (to prevent divide by zero) and when the look exits without converging. Instead of returning NAN in the second case, should it throw an exception?

**Comment by markrogoyski** [comment]
Throwing an exception when it doesn't converge seems reasonable, as the expectation of the function is to return a meaningful number.
Possible exception names:
* FunctionFailedToConvergeException
* TooManyIterationsException

I'd recommend picking an exception name that would be the most generally applicable.

**Comment by markrogoyski** [comment]
In a future release, I think I will restructure the Math exceptions. I think there could be two base MathPHP exceptions: one that extends RunTimeException, and another that extends LogicException. I think a lot of these kinds of cases would fall under [RunTimeException](http://php.net/manual/en/class.runtimeexception.php). Classifying them as RunTimeExceptions gives the caller the option of retrying or something. Whereas if it was a LogicException you know it is time to fail.
