### ISSUE TITLE
Gentlemen, can we add the multivariate distribution functionality?

### ISSUE THREAD

**Issue by xscheme** [markrogoyski/math-php#217]
I just start using this PHP Maths library. It is an amazing piece of work. I guess PHP not being widely used in Finance Industry is due to the lackness of Maths libraries. 

I notice so far there are 2 important functionalities missing:
1. the maths optimization function for univariate or multivariate functions
2. the multivariate distribution functionality

the second one is important to price multi-asset related options.

My maths/statistics background is not strong. Otherwise, I will contribute to these 2 libraries.

Hopefully, someone can pick this up.

**Comment by markrogoyski** [comment]
Hi. Thank you for your interest in MathPHP, and thank you for the feature request.

For 2), are there any specific multivariate distributions you would prioritize over others?

For 1), can you give some detail on how you envision this functionality working? For example, given input X, you expect output Y because it did process/function F.

Thanks for your input.

**Comment by xscheme** [comment]
Thanks, markrogoyski. I am using your library to implement exotic options pricing in PHP. I will publish this as another open source projects in GitHub to promote PHP in the finance industry. 

Let's focus on the second point first. 

What I need is the Multivariate Normal Distribution. 
https://en.wikipedia.org/wiki/Multivariate_normal_distribution

In my case, I need to compute the 2-variate normal distribution, e.g., the 2 variate have a correlation rho. I need to get the joint cumulative distribution for the region (-oo, d1) for the one variate, and  (-oo, d2) for the second variate.

Does this explain clearly what I want? Sorry, I am not maths/statistics student.

The matlab code is similar as follows:

mu = [0 0];
Sigma = [1 rho; rho 1];
d1 = 0;
d2 = 0;
mvnpdf([d1 d2], mu, Sigma);

**Comment by markrogoyski** [comment]
Thank you for the information. This is helpful. I agree this is a good feature to have. I will update this thread when this is implemented, or if there are any followup questions.

Thank you for the feature request.

**Comment by Beakerboy** [comment]
@markrogoyski How would you like to handle this? Should we make a Multivariate namespace? The matlab inputs are arrays of independent variables, averages, and the covarience matrix. Should we just expect arrays for all three?

**Comment by markrogoyski** [comment]
If there is a Multivariate namespace, it seems like there should also be a Univariate namespace. And if that is the case, what order do they go in?

Type\Variable or Variable\Type?

Probability\Distribution\Continuous\Univariate
Probability\Distribution\Continuous\Multivariate
Probability\Distribution\Discrete\Multivariate
Probability\Distribution\Discrete\Univariate

Vs.

Probability\Distribution\Univariate\Continuous
Probability\Distribution\Univariate\Discrete
Probability\Distribution\Multivariate\Continuous
Probability\Distribution\Multivariate\Discrete

Regarding the inputs to the Multivariate normal distribution, would two arrays and a Matrix work? Any reason the k x k covariance matrix would not be of Matrix type?

**Comment by xscheme** [comment]
Prefer this one:

Probability\Distribution\Continuous\Univariate
 Probability\Distribution\Continuous\Multivariate
 Probability\Distribution\Discrete\Multivariate
 Probability\Distribution\Discrete\Univariate

do not understand your second part.

The input to the Multivariate normal distribution should be 3 parameters:
1. the point (starting from -oo) for each axis;
2. the mean along each axis;
3. the covariance matrix between each pair of axis.

**Comment by markrogoyski** [comment]
As another option for the namespace organization, how about this:

Probability\Distribution\Continuous
Probability\Distribution\Discrete
Probability\Distribution\Multivariate

There aren't so many multivariate distributions, and this will avoid duplicate sub namespaces.

Thoughts?

**Comment by Beakerboy** [comment]
This would be my choice.

**Comment by markrogoyski** [comment]
@xscheme The multivariate normal distribution PDF has been implemented in [v0.34.0](https://github.com/markrogoyski/math-php/releases/tag/v0.34.0).

Thank you for the feature request. Please create a new issue if you have additional feature requests.
