### ISSUE TITLE
How to pass a group of arrays to the ANOVA::oneWay method

### ISSUE THREAD

**Issue by yuangao2** [markrogoyski/math-php#241]
The data for the test were retrieved from the database in the following format. Each sub-array is one data set in the ANOVA set (like $sample1, $sample2, etc.). The problem is the number of sub-array is not fixed depending on the input. So, I add them all into a big array during the query process.
Array
(
[0] => Array
    (
        [0] => 14.60
        [1] => 15.94
    )

[1] => Array
    (
        [0] => 16.12
        [1] => 15.30
        [2] => 9.24
    )

[2] => Array
    (
        [0] => 6.80
        [1] => 15.78
    )
)
The problem is that the ANOVA::oneWay method only accepts comma delimited arrays. Please provide guidance on how to pass the above array for the ANOVA test. Thank you very much.

**Comment by markrogoyski** [comment]
It looks like you have two data sets with 2 values, and one data set with 3 values. Right now the one-way ANOVA requires that all data sets have the same sample size (same number of values). If you can obtain data sets of equal sample size, then you can use the one-way ANOVA. Each data set would be in its own array.

For example:
```php
$data; // This is your dataset from your database.

$sample1 = $data[0];
$sample2 = $data[1];
$sample3 = $data[2];
$anova = ANOVA::oneWay($sample1, $sample2, $sample3);
```

So, if you can get a sample set with equal sample sizes, and put each data set into its own array, then you can use the one-way ANOVA function.

Does this answer your question?

**Comment by yuangao2** [comment]
Thank you very much for the quick reply. Sorry for not describing my problem clearly. Actually, my original problem is when I have a group of arrays wrapped in one big array, how I can pass that single array to the method. I don't know how many sub-arrays will be there, so I can not simply assign them to a list of arguments.
I also asked the question at stackoverflow. And I have received two solutions there:
1) use:  $anova = call_user_func_array([ANOVA::class, 'oneWay'], $data);
2) use:  $anova = ANOVA::oneWay(...$data);
I also noticed the one-way ANOVA requires that all data sets have the same sample size. If I do want to perform one-way ANOVA for data sets with different sample sizes, what shall I do? Thanks a lot.,

**Comment by markrogoyski** [comment]
Using the splat operator ```...$data``` is probably the most straightforward way.

Currently unequal sample sizes is not supported. I can add it to the feature backlog for consideration in an upcoming version.

**Comment by yuangao2** [comment]
Thanks a lot

**Comment by markrogoyski** [comment]
I've added an item to the development backlog for implementing one-way ANOVA with unequal sample sizes. This issue is captured in that backlog item.
https://github.com/markrogoyski/math-php/projects/1
