### ISSUE TITLE
Question about Lagrange and Numeric analysis

### ISSUE THREAD

**Issue by mj-mehdizadeh** [markrogoyski/math-php#243]
I have a series of (x, y) data  that I know is ascending, but I want to find the some numbers between them, i user Lagrange algorithm, the points i get are not ascending. Which algorithm should I use?
 
sample:

> My base data : 
 [![my data][1]][1]

> The points i expect : 
[![The points that i expect to get][2]][2]

> but with Lagrange i get this points : 
 [![the Lagrange output][3]][3]

  [1]: https://i.stack.imgur.com/8VDub.png
  [2]: https://i.stack.imgur.com/70dAo.png
  [3]: https://i.stack.imgur.com/Wdkkk.png

**Comment by Beakerboy** [comment]
Could you please provide the 6-point dataset?

**Comment by Beakerboy** [comment]
I know nothing about lagrange polynomials, but I read the wikipedia article and used excel with estimated values from your graph and got a result very similar to your results from the library. How did you calculate your "expected" values.

**Comment by mj-mehdizadeh** [comment]
The data is i expect is a sample, i want say i want to get to the sample data and i dont know which algorithm is best, i search and find out the lagrange is best algorithm, but it is not work for me,

> i have series data and i want to get the point like "points i expect"

sorry for bad English

**Comment by Beakerboy** [comment]
Would a logarithmic interpolation suffice (5958.2 * ln(x) + 380766)? I personally don't know what is "best", and it probably depends on what you want to do with your spline or regression. Someone else here may be able to help, but you might have more luck on [stack exchange](http://stats.stackexchange.com). Once you know what algorithm you need, check to see if our library has the necessary functionality. If we do not, we will add it to the list.

**Comment by markrogoyski** [comment]
@Beakerboy Thanks for following up with suggestions.

@mj-mehdizadeh Thanks for your interest in MathPHP.
Try using ```MathPHP\Statistics\Regression\PowerLaw``` with your points and then evaluating to see if you get results resembling what you were expecting. I think if the Power Law regression equation calculates an exponent of < 1 you should get a curve that looks like what you expect.

For example:
```php
$regression = new Regression\PowerLaw($points);
$y = $regression->evaluate($x);
```

And like @Beakerboy said, if there is an algorithm or regression or something that you need, let us know.

**Comment by mehdizadeh-mj** [comment]
@markrogoyski Thank you it is work
