### ISSUE TITLE
Add standard error estimates on regression parameters

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#25]
The regression will have standard errors for each parameter. How would we like to return these? Array? what about for other regression types, Multiple, polynomial, etc?

**Comment by markrogoyski** [comment]
Array sounds good. Should be in the same order as the variable. I haven't put any thought into multiple/polynomial/etc. regressions. What do you suggest? We can always refactor later if a better idea comes up.

**Comment by Beakerboy** [comment]
Standard Errors, T values, T probabilities, F value, and F Probability has been added.
In a pull request.
