### ISSUE TITLE
Harmonic numbers

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#254]
Where would you like me to put a function of harmonic and generalized harmonic numbers:
Sum k=1 to n (1/k)
I’m going to add the Zipf’s Law discrete distribution.

**Comment by markrogoyski** [comment]
There is the namespace ```Sequence``` for sequences of numbers. I admit it is not well organized, but that seems like a good place.
If you are computing the sum, then we probably need a new namespace ```Series```.

**Comment by Beakerboy** [comment]
The header of each of the sequence classes seems to imply that all of the sequences are integer sequences and Harmonic numbers are not integers.  I don’t know if this matters to you or not.

**Comment by markrogoyski** [comment]
Harmonic numbers are a sequence. I think it is fine to go there.

**Comment by Beakerboy** [comment]
#300 submitted
