### ISSUE TITLE
Add Calculus functionality

### ISSUE THREAD

**Issue by peter279k** [markrogoyski/math-php#258]
Hi @markrogoyski, thank you for this great math project.
As title.
Implement the Differential and Integral method.
Here is my thought:
- for example, declare the equation: ```x^2 + x + 1```.
- this equation maps the two arrays. One is [1,1,1] and another one is [2,1,0].
- do the one step Differential and result arrays are [1*2, 1*1, 1*0] and [1,0,0].
- the same approach is for Integral.
What do you think?

Thanks.

**Comment by Beakerboy** [comment]
The solution I propose is to add a derivative method the the Polynomial class which would return an object with the correct parameters. The integral is more difficult because if the “+C”. Maybe the user would have to provide the value of the constant as input.

**Comment by Beakerboy** [comment]
...and I just looked at the code to see that the requested functionality already exists in that class. Let us know if that does not meet your needs.

**Comment by markrogoyski** [comment]
As @Beakerboy mentioned, the Polynomial already has integration and differentiation functions.

Would it be more easily discoverable if we had a Calculus namespace and had a wrapper class in there for the Polynomial?

**Comment by peter279k** [comment]
Ok, thank you for @markrogoyski and @Beakerboy .
I see that the Numerical Differentiation and Numerical Integration section.
It's very closed my requested functionality and this issue will be closed.

**Comment by markrogoyski** [comment]
Hi @peter279k 
While there are numerical analysis methods to do differentiation and integration, there is also a Polynomial class that does this which is closer to what you are suggesting in your original request.

Check out MathPHP\Functions\Polynomial.

It isn't documented in the README as it is used mostly for internal implementations but it can be used for polynomial arithmetic and calculus.

I will consider how to document usage of this class and perhaps add a Calculus namespace as well.

**Comment by peter279k** [comment]
Hi  @markrogoyski. Thank you for your reply. I have found the useful example in this PHP [file](https://github.com/markrogoyski/math-php/blob/3137abc283c341488bb91493894409329cf01012/src/Functions/Polynomial.php).
I think this is the great example in this file and it should add this in the README.

Thanks.
