### ISSUE TITLE
Descriptive::percentile fails with Undefined offset: -1

### ISSUE THREAD

**Issue by neFAST** [markrogoyski/math-php#261]
Here is a fiddle
http://sandbox.onlinephpfunctions.com/code/2a2247a92d04a0206537ebe49d080f1f88a04aba

The function checks for P<0 and accecpts a zero value. But it ends up accessing offset -1 of the array

**Comment by markrogoyski** [comment]
Thanks for the feedback and providing an example. This seems like a lower bound issue. For the zeroth percentile we probably don't need to calculate the ordinal rank and just use the smallest value. Or, perhaps it makes sense for percentile to only accept values between 1 and 99 inclusive. I'll do some investigation on this issue. Thanks for reporting.

**Comment by Beakerboy** [comment]
Is there a reason $P is an int? Why should a user not be able to request the 50.5th percentile?

**Comment by markrogoyski** [comment]
Thanks for the feedback.
I've reimplemented percentile using the more robust linear interpolation between closest ranks method - Second variant, C = 1. Boundaries 0 and 100 now work properly. Percentiles of any number between 0 and 100 can be calculated, including floats like 50.5th percentile.

The updated method is currently in the develop branch:
https://github.com/markrogoyski/math-php/blob/develop/src/Statistics/Descriptive.php#L454

I've added much more exhaustive unit test cases to give a higher confidence that the function is working correctly.

Updated unit tests:
https://github.com/markrogoyski/math-php/blob/develop/tests/Statistics/DescriptiveTest.php#L427

Please check it out and let me know if you have any additional feedback. This will be included in the next release.

**Comment by neFAST** [comment]
Great! Thanks a lot. Second variant seems to work fine!

**Comment by markrogoyski** [comment]
This change has been included in the latest release, v0.38.0.

Thank you for bringing this issue to our attention. Thank you for your continued interest in MathPHP.
