### ISSUE TITLE
Simple Linear Regression memory usage

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#262]
I was using MathPHP to perform a simple linear regression with a couple thousand data points and have been running into memory issues. To solve this, I calculated the slope and intercept using the algebraic method and it worked fine. I was thinking that I would make a new Least Squares trait called LeastSquaresAlgebraic. The idea would be to use the algebraic algorithm instead of the matrix algorithm to reduce all the overhead in the matrix class.

Alternatively, do you have any suggestions on how we can refactor some of the classes to reduce memory use?

**Comment by markrogoyski** [comment]
Can you provide a data set that reproduces the problem?

Also, the original implementation of linear regression was the algebraic solution =)  The Matrix solution is nice though. Let's see if we can make it perform better.

**Comment by Beakerboy** [comment]
I'd rather not provide my data...sorry (proprietary stuff). The reason I changed it from algebra to matrix math was to allow the method to be extendable to multiple linear, regression through the origin, and polynomial, so yeah, I see the irony as well.

**Comment by markrogoyski** [comment]
Sure, no worries. Can you give an idea of how many items and the size of each item so I can create a similarly sized data set to try to reproduce the problem?

**Comment by Beakerboy** [comment]
I'll close this for now. if it pops up again I'll dig into it some more.
