### ISSUE TITLE
tTestTwoSample will fail for some value combinations

### ISSUE THREAD

**Issue by pstamb** [markrogoyski/math-php#265]
```
use MathPHP\Statistics\Significance;
$tTest = Significance::tTestTwoSample(32, 30, 134, 210, 21, 18);
print_r($tTest);
```
Output:
[Many division by zero errors]
Array ( [t] => -3.6386565925866 [p1] => -INF [p2] => -INF )

**Comment by markrogoyski** [comment]
Hi @pstamb,
Thank you for your interest in MathPHP, and thank you for reporting an issue.

I was able to reproduce a division by zero when computing the p1 after computing the t statistic. I'll take a look at what is going on and see what I can do to make this more robust.

Also, I have some planned improvements for the t-test, so I will use this opportunity to implement those improvements. For example, one option that would be useful to have available is the option to pass two arrays of data instead of precomputing the means, Ns, and standard deviations.

**Comment by pstamb** [comment]
Hi @markrogoyski, 
Thank you for the swift response. Indeed sending all the data would be very helpful to me too. 

BTW, have you decided on a policy for what to do with errors in the inputs that would cause the calculation to fail (I mean like non-numeric or null data, n < 2, 0 variance in a sample)? 

I mean it's a library for a programming audience, it wouldn't hurt to do our own error checking, I just think it should be clear who is expected to do it.

**Comment by markrogoyski** [comment]
Hi @pstamb,

Version 0.40.0 has been released with improvements to the t test. Please try it out and let me know if you still experience any issues.

Also, the interface has been improved. Now you have the option to provide the same data as input, or the summary data. In addition, more information is provided in the test output. For example:

```php
// T test - Two samples (from sample data)
$x₁    = [27.5, 21.0, 19.0, 23.6, 17.0, 17.9, 16.9, 20.1, 21.9, 22.6, 23.1, 19.6, 19.0, 21.7, 21.4];
$x₂    = [27.1, 22.0, 20.8, 23.4, 23.4, 23.5, 25.8, 22.0, 24.8, 20.2, 21.9, 22.1, 22.9, 20.5, 24.4];
$tTest = Significance::tTest($x₁, $x₂);
print_r($tTest);
/* Array (
    [t]     => -2.4553600286929   // t score
    [df]    => 24.988527070145    // degrees of freedom
    [p1]    => 0.010688914613979  // one-tailed p value
    [p2]    => 0.021377829227958  // two-tailed p value
    [mean1] => 20.82              // mean of sample x₁
    [mean2] => 22.98667           // mean of sample x₂
    [sd1]   => 2.804894           // standard deviation of x₁
    [sd2]   => 1.952605           // standard deviation of x₂
) */

// T test - Two samples (from summary data)
$μ₁    = 42.14; // Sample mean of population 1
$μ₂    = 43.23; // Sample mean of population 2
$n₁    = 10;    // Sample size of population 1
$n₂    = 10;    // Sample size of population 2
$σ₁    = 0.683; // Standard deviation of sample mean 1
$σ₂    = 0.750; // Standard deviation of sample mean 2
$tTest = Significance::tTestTwoSampleFromSummaryData($μ₁, $μ₂, $n₁, $n₂, $σ₁, $σ₂);
print_r($tTest);
/* Array (
   [t] => -3.3972305988708     // t score
   [df] => 17.847298548027     // degrees of freedom
   [p1] => 0.0016211251126198  // one-tailed p value
   [p2] => 0.0032422502252396  // two-tailed p value
   [mean1] => 42.14
   [mean2] => 43.23
   [sd1] => 0.6834553
   [sd2] => 0.7498889
] */
```
