### ISSUE TITLE
ZScore Documentation is hard to read

### ISSUE THREAD

**Issue by xmas** [markrogoyski/math-php#271]
The Current documentation is written as this:

```
// Z score
$M = 8; // Sample mean
$μ = 7; // Population mean
$σ = 1; // Population SD
$z = Significance::zScore($μ, $σ, $x);
```

This is confusing as $M is not referenced, and $x is not described... I believe it should be used as:

```
// Z score
$M = 8; // Sample mean
$μ = 7; // Population mean
$σ = 1; // Population SD
$x = false; // Raw Value or not
$z = Significance::zScore($M, $μ, $σ, $x);
```

**Comment by markrogoyski** [comment]
Hi @xmas,
Thank you for reporting this. You are correct. The documentation has not been updated as the implementation has changed. The documentation will be updated in the next release.

Thank you for your interest in improving MathPHP!

Mark

**Comment by markrogoyski** [comment]
This has been fixed in the latest version, [v.0.44.0](https://github.com/markrogoyski/math-php/releases/tag/v0.44.0).

Thank you for your continued interest in MathPHP!
