### ISSUE TITLE
how should i multiply a Two-dimensional array with a One-dimensional array？

### ISSUE THREAD

**Issue by yuzhiyuan** [markrogoyski/math-php#285]
like this
$x = [[10, 10, 10, 10],[10, 10, 10, 10],[10, 10, 10, 10],[10, 10, 10, 10]];
$y = [1,   2,  5, 10];
could id use  Map\Multi::multiply($x, $y)?
it throw a fatal error Uncaught Error: Unsupported operand types in .../Functions/Map/Multi.php:87
thank you

**Comment by markrogoyski** [comment]
Hi @yuzhiyuan,

As @Beakerboy pointed out, you could use ```Map\Multi::multiply``` in a for loop. Or, you could use a PHP ```array_map``` to map the multiplication of the ```$y``` array onto each element of the ```$x``` array.

```php
$xs = [[10, 10, 10, 10],[10, 10, 10, 10],[10, 10, 10, 10],[10, 10, 10, 10]];
$y  = [1, 2, 5, 10];

$result = array_map(
    function ($xs) use ($y) {
        return Map\Multi::multiply($x, $y);
    },
    $xs
);
```
