### ISSUE TITLE
Truncate Decimals Frature

### ISSUE THREAD

**Issue by specialtactics** [markrogoyski/math-php#286]
Hi there

I had a requirement in a project recently to be able to truncate decimals from a number without rounding - ie. regardless of whether it would normally be rounded either up or down, the result should be the same - no rounding.

For example, if we wanted to truncate to 2 decimal places, the results for the following 2 numbers would be the same:

1.239 = 1.23
1.231 = 1.23

To my surprise, I couldn't find this sort of functionality in PHP nor any popular maths libraries - because they all insisted on rounding.

So I wrote a function to implement this functionality (along with tests), as it's not very complicated.

I am wondering whether you would accept this sort of thing into this library? I have considered that it can also be said to fit into string manipulation rather than math, but to me and for my purposes, it is strictly a mathematical operation (dealing with financial data).

If you would be happy to have it, I'd be happy to do a PR. Just suggest where I would place such a function, and if you have any name suggestion better than "truncateDecimalNumber", go ahead :)

**Comment by markrogoyski** [comment]
Hi,

Thanks for your interest in MathPHP.

If you think this is a financial-related operation, you could put it in the ```MathPHP\Finance``` class. Otherwise, perhaps the ```MathPHP\Arithmetic``` class would be a good general fit.

What do you think?

**Comment by specialtactics** [comment]
@markrogoyski Sounds good, I will submit a PR for your review
