### ISSUE TITLE
Automated Documentation

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#288]
I've been playing around with NaturalDocs on another project. Have you thought about enabling automated doc generation and hosting docs on Github? 

Here's an example of a few of our classes in NaturalDocs.

https://beakerboy.github.io/math-php/

**Comment by markrogoyski** [comment]
I have not looked into it yet, but for sure by the time we release a 1.0 version we should consider documentation beyond the main README. We could definitely try setting it up and see how it works. What are the pros and cons of NaturalDocs compared to competitors, if there are any?

**Comment by Beakerboy** [comment]
NaturalDocs seems to support more languages, be simpler to extend to new languages, but is a more manual process. The resulting pages are supposed to look better than Doxygen. One advantage of Doxygen is native LaTeX support, which would make documenting mathematical functions much simpler. Between the two, I would vote Doxygen, just due to the LaTeX support.

It looks like there are scripts which allow devs to just push code to the repository, and Travis will run the Doxygen generation and push that back to GitHub.

**Comment by Beakerboy** [comment]
There's a doxygen service that will automatically generate the documentation and host it off github, like travis and coveralls:
https://codedocs.xyz/Beakerboy/math-php/

Interestingly, this service is used by the doxygen project itself.

**Comment by markrogoyski** [comment]
Cool. I'll check it out. I'll also investigate what other solutions are available. Automation with CI I think is an important requirement.

**Comment by Beakerboy** [comment]
In summary, I’ve tested:

- Doxygen-as-a-service
- NaturalDocs manual generation
 - NaturalDocs generated by Travis and pushed to a gh-pages branch.
