### ISSUE TITLE
Prime Factorization return format

### ISSUE THREAD

**Issue by spyder21er** [markrogoyski/math-php#293]
Instead of returning an array of prime factors.
```
$Integer::primeFactorization(128); // = [2, 2, 2, 2, 2, 2, 2] (2^7)
$Integer::primeFactorization(72); // = [2, 2, 2, 3, 3] (2^3 * 3^2)
```

What do you think of formatting it as [key => value] pair of [prime => power] such as below:
```
$Integer::primeFactorization(128); // = [2 => 7]  (2^7)
$Integer::primeFactorization(72); // = [2 => 3, 3 => 2] (2^3 * 3^2)
```

Does it save memory space for bigger powers? 

We can also encapsulate it to manage the formatting for printing.

**Comment by markrogoyski** [comment]
Hi @spyder21er,

Thanks for your interest in MathPHP and wanting to improve it!

Regarding the interface of prime factors and what it should return, just based on the name I would think one would expect it to return the prime factors of the number provided, as it currently is.

Looking at other mathematical libraries, this is the common return value. 

For example, here is the function in the R programming language:
```R
> primeFactors(128)
[1] 2 2 2 2 2 2 2
```

SymPy in Python does it a little bit differently:
```python
>>> sympy.primefactors(128)
[2]
```
It returns only the unique prime factors, which you can easily do with MathPHP's version by using it as input to an ```array_unique``` call.

```php
$primeFactors = array_unique(Integer::primeFactorization(128));
```

Based on this, I think it is appropriate and flexible to many use cases as it currently is.

Thanks again for the input. Please don't hesitate to ask other questions or provide any other suggestions you might have.
