### ISSUE TITLE
Data direction standard

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#296]
It looks like we have a few methods which operate under the assumption that the source matrix will be organized with variables in the m direction and samples in the n. For example, `sampleMeans()` averages each row. 

It looks like both R and Matlab operate u beer the opposite standard, but numpy uses what we have. Personally I vote for what R and Matlab do since that’s how I organize data in a spreadsheet and it seems more intuitive. What do you think?

**Comment by markrogoyski** [comment]
For implementing Matrix ```sampleMean```, I referred to my old college textbook _Linear Algebra and Its Applications_ (Lay) Second Edition. The example in the PHP doc block is taken exactly from the textbook.

I personally don't have an opinion. Let's do whatever is more standard, whatever that means.

Other than ```sampleMean```, what other methods would need to change?

**Comment by markrogoyski** [comment]
Thinking about this a little more, I think it makes sense that NumPy (and MathPHP) would do this differently from R and Matlab. With R, you are more likely to be working with the data hands on, whereas with Python it is probably all programmatic/automation that is doing computations. So NumPy makes it easy to work with data programmatically. For a two-dimensional array, which is basically what a Matrix is, it makes sense based on how you'd access each element. It is usually unnatural to access data sequentially across different arrays.

I think NumPy is probably taking a programmer-first approach, whereas R/Matlab take a mathematician-first approach. The question then, is what is the MathPHP philosophy on this. I'd probably try to weasel out some middle-of-the-road answer that it should make sense to mathematicians and be natural to work with programmatically.

Would it over complicate things to make this configurable? After you create a matrix, maybe you can call a setter method that configures the data direction? Up until now the Matrixes have been immutable and always creating new Matrices when there is some sort of calculation, but this kind of thing would be OK to simply change the internal state (configuration) of the matrix. I was also thinking about doing something like this to have the Matrix configurable in terms of what its threshold is to consider something equivalent to zero.

**Comment by Beakerboy** [comment]
What got me started on this question was my work on a PCA class. PCA seems to always start with a data matrix with each sample in a row and each variable in a column. However when starting to work on this process with our library I was having problems with the covariance matrix and eventually noticed it was because my data was “backwards”.

On first blush, the sameMeans and related functions, and the covarience method are the only ones that I can think of which may need to be changed. I would have to look at how linear regression works, it might need to too.

One motivation for change is how modern data is stored and retrieved. When data comes from a database it will typically be samples in rows and variables in columns.

My suggestion is to make that change, and if a user makes a request, figure out how to make it configurable.

**Comment by markrogoyski** [comment]
I have an alternate solution for this.

I am thinking about removing the `sampleMean` method, and replacing it with two new methods: `rowMeans` and `columnMeans`. 

`rowMeans` would work exactly as `sampleMean` currently does, whereas `columnMeans` would go in the other direction.

Then, I think `meanDeviation` and `covarianceMatrix` could have an optional parameter to set the direction, which internally would determine if it calls `rowMeans` or `columnMeans`.

**Comment by Beakerboy** [comment]
Sounds good

**Comment by markrogoyski** [comment]
I am thinking of having a method on the matrix to change the data direction. Something like ```$matrix->setDirection(...)```

My question, is what do I call the two options? 
```php
$matrix->setDirection('row');
$matrix->setDirection('column');
```

Is there a better way to describe this that is obvious and intuitive?

**Comment by Beakerboy** [comment]
I don’t like “setDirecrion” because it is arbitrary. It needs to be directly obvious that it is dealing with samples and variables. Maybe something like this:

````php
function setSamplesIn($row_or_column) {
    if ($row_or_column !in_array([‘row’, ‘column’]) {
        throw exception;
    }
    $this->rowSamples = $row_or_column === ‘row’;
}
function setVariablesIn($row_or_column) {
    if ($row_or_column !in_array([‘row’, ‘column’]) {
        throw exception;
    }
    $this->rowSamples = $row_or_column !== ‘row;
}
````

**Comment by markrogoyski** [comment]
Yeah, I'm not happy with direction either, which is why I need some help naming this.

If I think of data in Excel or a database, I have columns which represent different data, and then each row represents a sample which contains the data. So I would say the columns represent the variables and each row is a sample.

Now, if I wanted to flip that around, how do I word that? Maybe a generic function isn't best, and maybe two idempotent functions for setting the data in the arrangement you want is best.

```php
$matrix->setColumnsAsVariables();

$matrix->setRowsAsVariables();
```

Does this seem more intuitive as to what they do? At least you don't need to know what the right values are for the parameter. Thoughts?

**Comment by markrogoyski** [comment]
I will work on this next. I'll submit a pull request for you to review. I'm just going to keep it simple for now.

**Comment by Beakerboy** [comment]
I have a set of VBA functions that allow me to do some if this stuff in excel. In that, I have a Matrix object that can do math, but I also have a DataSet object that allows me to add metadata to a matrix. I can add sample names and variable names, and define what direction the data is. The object will transpose one into the other as needed.

**Comment by markrogoyski** [comment]
I have been thinking about whether a DataFrame type object makes sense in this library. And how would it differ from a Matrix. Or would it make sense to make a Matrix "smart." R keeps the numerical Matrix and DataFrame as separate concepts. The main difference is that a Matrix in R only has numbers, while a DataFrame can have numerical variables and string categorical variables. I think Python does a similar distinction within the Pandas library.

So for now, I think making the Matrix slightly configurable for the direction of the numerical variables/samples might make the most sense. Conceptually a Matrix is immutable in terms of its values, but configurable in terms of say the data direction and the error tolerance. Another option is to just set it in the constructor and it becomes completely immutable.

**Comment by markrogoyski** [comment]
I started implementing this, and then changed my mind as I was doing it. I started making a configuration for the matrix to set a direction of variables/samples, but I think it starts to overcomplicate things. If you want `meanDeviation`, for example, to work a certain way, you have to know to call some other method first that causes a side effect later on.

I think the simplest solution is the best for now. I'll just add an optional parameter to `meanDeviation` and `covarianceMatrix` to set if it works against rows or columns, and have it default to rows.

Does that sound reasonable?

**Comment by Beakerboy** [comment]
Sounds good.

**Comment by markrogoyski** [comment]
This has been implemented in the develop branch.
