### ISSUE TITLE
Planning for Stable Version 1.0 Release

### ISSUE THREAD

**Issue by markrogoyski** [markrogoyski/math-php#298]
After two and a half years of development, it is time to start planning for a stable version 1.0 release.

**What does it mean for MathPHP to achieve the version 1.0 milestone?**
- Officially released
- Ready for general use
- A solid initial feature set
- High confidence in all features
- The API is stable (Point releases aren't going to fundamentally change a method signature or return value)
- No known outstanding bugs
- Beyond 100% unit test coverage
- Some form of documentation

**What features are missing?**
This is an open question I'd like to get feedback on. Now, we know what features are missing. There is a lot of math still to be implemented. The question is, what features that are yet to be implemented, absolutely should be included in version 1.0? I'm not asking what you'd like to see one day in a future version. I'm asking, what is the basic functionality you'd expect from a math library, that if it wasn't there, it would be surprising? For example, you'd probably expect standard deviation or mean/median/mode calculations in any math library, but not necessarily some obscure elliptic curve cryptographic functions.

Version 1.0 is just a milestone, and development of 1.x and eventually 2.0 will continue to add new features. But we have to cut and release 1.0 at some point. So, are we missing anything that 1.0 absolutely needs? Let me know your feedback on this one.

**Technical Details**
Version 1.0 and continuing 1.x releases will continue to target PHP 7.0 as a minimum version.

**Comment by Beakerboy** [comment]
Essential:
- Finalize Eigenvalues
- PCA. Once JK algorithm or QR eigenvalue algorithm are in, PCA can be merged.

Here are the features I am working on. I don't feel any are essential, but if you do, let me know:

- Large Numbers. My initial purpose is to calculate the Lanczos constants that we just blindly use. Initially I was implementing 128 bit integers, but I think following the bcmath strategy and using arbitrary length strings would be better.

- Studentized Range for Tukey....Requires a few numerical integration steps, so it might be more worthwhile to just type in a table and use interpolation.

A couple suggestions:

- Example Data...I imported a copy of the R mtcars dataset to use in my PCA unit tests. I might be helpful to have other "standard" data somewhere for people to use in tests.

- Matrix class size. The Matrix class is becoming very large. Would it be possible to move some algorithms to static classes and have the Matrix call them if needed? For example, we could move all the decompositons to other classes, and call
````php
$mat = new Matrix;
$mat->decompose("QR_HOUSEHOLDER")
```` 
Currently the matrix has $L, $U, and $P as properties. We could have `$decompositions` and instead have:
````
$this->decompostions =
    'LUP'=> [
        'L' => $L,
        'U' => $U,
        'P' => $P,
    ],
    'QR' => [
        'Q' => $Q,
        'R' => $R,
    ],
    'SVD' => [
       'U' => $U,
        'D' => $D,
        'Vstar' => $V->transpose(),
    ]
];
````
- @jakobsandberg added some great functions, but the format is a little different than other functions that we have. Some classes have `@todo` tags that should be checked.

- Make a decision on column vs rows for samples and verify that the standard is used everywhere.

- Go through the issues queue and tag them as a goal for v1.0, v1.x, or v2.x.

- Project Website...GitHub can host static files from the ghpages branch. It would be pretty cool to be able to use the @jakobsandberg plotting branch to demonstrate MathPHP in action, like graphing probability distributions, or specialized functions.

**Comment by markrogoyski** [comment]
Thanks for your feedback, @Beakerboy.

**Essential Functionality**
I agree about the matrix functionality. Let's do QR decomposition and eigenvalues. I don't know enough about Principal Component Analysis, but I trust your judgment so let's try to do that as well.

**Suggestions**
Example data - Yes! I try to use any example data I can find for unit tests. If there are good data sets out there for any functionality in MathPHP, please make a suggestion, and provide a link if available. I will happily write unit tests using the data. I have been trying to use a thorough and exhaustive use of general examples, edge cases, and axioms in unit tests to give confidence that everything works. The entire suite of unit tests runs ridiculously fast, so adding more example data for tests is no problem at all.

For example, a full test suite run on my Mac:
```
Time: 3.8 seconds, Memory: 74.01 MB

OK (13561 tests, 23758 assertions)
```

Matrix class size - Yes, I agree that the Matrix class is large. I have been planning to refactor it once QR and maybe eigen functions are done. I was thinking the same thing about having some Decomposition classes. I was also considering holding off until version 2.0, because I want to change some of the return values from arrays to objects, but don't want to break the API. I'm considering the current version close enough to 1.0 that it should stay that same for now.

Milestone tags - I've already created a milestone 1.0 tag and tagged some things as that. If you think there is a 1.0 blocker issue in the issue list that isn't tagged leave a comment and I'll add it.

Columns vs rows - Yes. We have a separate issue tracking this. I'll take on this once I do a little more research into it.

Project Website - Things I'm looking at are documentation and a project logo. I'd like documentation to show enough examples of each function to show how its used and what kinds of values to expect. The current README does not really explain anything, nor provide more than a single example, and often without showing what the return value is. One option is to put all of this in the PHPDocs, but I'd like to keep the code clean and readable, so I thinking a separate documentation/examples site is probably the way to go. I'm still looking around to see what all the options are. This is probably more of a long term project and fully documentation everything should not be a 1.0 release blocker.

**Comment by markrogoyski** [comment]
Hi @Beakerboy,

For your suggestion about sample data sets, I like it. I'm thinking to make a `MathPHP\SampleData` namespace that is available for general use, not just in the unit test directory.

My question is, what sample data would be good to start off with in an initial version? There already is _mtcars_. Are the other R built-in data sets good to include. For example, R has the _iris_ and _ToothGrowth_ and _PlantGrowth_ and _USArrests_, among other sample data sets. Are these good ones to add, or did you have other data sets in mind?

Thanks.

**Comment by Beakerboy** [comment]
I see the iris data used a lot in examples, that one might be the next one to import. I think my original post was more of a “what’s out there” sorry of question. I know image processing and 3D rendering both have their own families of standard data, but I don’t know about statistics.

**Comment by markrogoyski** [comment]
@Beakerboy,
Per your suggestion, in the latest release I've added a `SampleData` namespace that contains some famous common data sets:
- MTCars
- Iris
- PlantGrowth
- ToothGrowth
- USArrests

**Comment by markrogoyski** [comment]
PCA, sample data, arbitrarily large integers, etc. are all implemented. Matrix refactoring will happen later. 

@Beakerboy, Any other suggestions for a must have to call it V1.0? How about the two pull requests for Matrix SVD and Eigenvalue decomposition?

**Comment by Beakerboy** [comment]
Go ahead without. Release early...release often.

**Comment by markrogoyski** [comment]
Cool. Thanks for the update. I'm going to clean up some older style issues and then call it good for  V1.0.0.

**Comment by markrogoyski** [comment]
v1.0.0 has been released. Closing this as completed.
