### ISSUE TITLE
$int is not initiated before use

### ISSUE THREAD

**Issue by fellek** [markrogoyski/math-php#299]
$int should be initiated before use, like all other variables too. 

Please just add this line into the Initialize part
`        $int = [];`

https://github.com/markrogoyski/math-php/blob/41d56a7542233cbb0489e7982facdb1d88d8c08b/src/NumericalAnalysis/Interpolation/NaturalCubicSpline.php#L112

**Comment by markrogoyski** [comment]
Hi,

Thank you for your interest in MathPHP and wanting to improve it!

I've added the array initialization. The changes are merged in the develop branch and will be part of the next release, v0.50.0.

FYI, PHP has a feature called autovivification, where it will automatically create arrays on assignment, which is what was happening in this case. However, I agree it is often better to be explicit in the code, so I've added the initialization lines.

For reference: https://en.wikipedia.org/wiki/Autovivification

**Comment by fellek** [comment]
Hi Mark,
thanks for your fast answer!
Yes, I agree in your opinion according to autovivification. As I started testing the library with some Arrays (of high numbers as x, floats as y) it throws some Exceptions, one of them blamed me of using an (NULL) Value in Piecewise::__construct(NULL, Array).
This Exception didn't appear anymore after adding 
$int = [];

I was a little bit irritated of this, but now it works as intended.

Thanks for supporting!

Fellek

Am 3. April 2019 05:54:09 MESZ schrieb Mark Rogoyski <notifications@github.com>:
