### ISSUE TITLE
Confidence interval and prediction interval of a regression

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#3]
I'd like to add these two statistics to your package and I would like your input on how you would like the results presented. 

The confidence Interval requires a set of $points, as well as an α...or 1-p. I could either return an array of confidence intervals evaluated at each x in the $points array, or make the user provide an $x to evaluate at.  Maybe the last is better, and if the user want the former, they could use array_map on $points,

Let me know what you think,
Kevin Nowaczyk

**Comment by markrogoyski** [comment]
Hi Kevin,
Thanks for the interest and help!

I think I'd prefer providing an x to evaluate at and allow the user to map over it like you said if they want an array of points. If you have a good argument to do it the other way please let me know.

Also, there is a standard confidence interval in Math\Statistics\RandomVariable if that is of any help. Also, we should standardize as much as possible so similar functions in different areas work in similar ways/return similar types of data.

Thanks.
Mark

**Comment by Beakerboy** [comment]
I have just added confidence intervals and prediction intervals to the Linear regression. Pull request in The queue.
