### ISSUE TITLE
Diagonal elements of a non-square matrix

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#302]
Currently the library returns an empty array of the matrix is not square. Would it be better to either throw an exception, or require the user to check for `isSquare()`? I was working on moving some code from Matrix to SquareMatrix, but there is a test to ensure that `getDiagonalElements()` returns [] from [[0, 1]].

My suggestion would be to replace this method with getMainDiagonalElements() in the Matrix class and move getDiagonalElements to the SquareMatrix class. This way, the class will always return something meaningful, even if the matrix is not square.

However, superdiagonal and subdiagonal elements seem to be completely unimportant in a non-square matrix, so I propose moving them without replacement.

**Comment by markrogoyski** [comment]
I think returning nothing for a non-square matrix was a mistake. I think `getDiagonalElements` should always return the "main diagonal", even if it is not square.

R does is that way:
```
> A = rbind(c(1, 2, 3), c(2, 3, 4), c(3, 4, 5), c(4, 5, 6))
> A
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    3    4
[3,]    3    4    5
[4,]    4    5    6
> diag(A)
[1] 1 3 5
> 
> 
> A = rbind(c(1, 2, 3, 4), c(2, 3, 4, 5), c(3, 4, 5, 6))
> A
     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    2    3    4    5
[3,]    3    4    5    6
> diag(A)
[1] 1 3 5
```

I can make this change when I have time if it is not blocking you to do other stuff. If you want to do it let me know so we don't both make the same change.

For the super/sub diagonal elements, it makes sense for those to be SquareMatrix-only methods.

**Comment by Beakerboy** [comment]
#304 submitted
