### ISSUE TITLE
isSymmetric and isSkewSymmetric

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#309]
These checks can be made to use half the memory and half the time. Instead of transposing and then comparing all elements, compare the values of the upper triangle with the lower triangle within $this.

**Comment by markrogoyski** [comment]
Good idea.

Check out branch _matrix-symmetric_ commit 555f4f2b2b3eb53d823f09e32852456cb8129a86:

Is this what you had in mind?

**Comment by markrogoyski** [comment]
Both methods have been refactored to use a more efficient algorithm. Changes are in the develop branch and will go out with the v0.50.0 release. Thanks for suggesting this.
