### ISSUE TITLE
Why can columnMultiply on multiply by integers?

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#312]
Looking at the Matrix methods, and I see that rowMultiply and columnMultiply each accept two ints, one which specifies the row or column and one for the number to multiply by. Why not a float?

**Comment by markrogoyski** [comment]
Yeah. It multiplier should be a float.

**Comment by markrogoyski** [comment]
I've updated all the row and column operations to work with floats. See https://github.com/markrogoyski/math-php/commit/9a8cb8135d1f1a8a623c682b6777db33e164bca2 in the develop branch.
