### ISSUE TITLE
Cannot load the library

### ISSUE THREAD

**Issue by lerotham** [markrogoyski/math-php#319]
Hello !

I followed the instruction to install math-php with Composer, and the installation seems correct, but when I want to use it, I get an error 500. For exemple with this code : 

```
require_once(__DIR__ . '/vendor/autoload.php');
use MathPHP\NumericalAnalysis\Interpolation;
 
$points = [
      [1499173200, 1.07],
      [1499176800, 1.6],
      [1499180400, 1.0],
      [1499184000, 0.31],
];
$p = Interpolation\NaturalCubicSpline::interpolate($points);
$p(1499173200) // 0.0 (1.07 expected)
$p(1499176800) // 0.0 (1.6  expected)
$p(1499180400) // 4.0 (0.31 expected)
```
 

So I tried to run phpunit in the directory tests and I got this message :

> PHP Fatal error:  Trait 'MathPHP\Tests\LinearAlgebra\MatrixDataProvider' not found in /var/www/html/vendor/markrogoyski/math-php/tests/Probability/Distribution/Multivariate/NormalTest.php on line 10

I'm sorry, this may be very basic but I've been looking for a solution since hours.

Thank you !

Jean

**Comment by markrogoyski** [comment]
Hi,

It sounds like you are loading a Web request and using MathPHP in your Web request. It looks like you have a syntax error in your code which would explain the HTTP 500.

```php
$p(1499173200) // 0.0 (1.07 expected)
$p(1499176800) // 0.0 (1.6  expected)
$p(1499180400) // 4.0 (0.31 expected)
```
You need semicolons after each method call here.

You can try `php -l filename.php` to do a basic syntax check of your PHP files. Or you can turn error reporting on in your php.ini to get better error reporting in your Web request output.

For better assistance, you might want to try one of the PHP reddit forums or StackOverflow to help with these kinds of issues as they are language/environment issues and not an issue with this library.

**Comment by lerotham** [comment]
Thank you Mark for your quick answer and your tips ! 

You're right, this was a bad example, but adding the semicolons doesn't solve the problem. I tried a lot of very simple examples. The problem is that it doesn't load the library at all. As I told you, phpunit failed too. Maybe I can give you an access to my server, so that it's easier for you to see ?

**Comment by markrogoyski** [comment]
I suggest you check your Web server error log, or learn how to turn PHP error reporting on and have it display the error in your Web request. PHP usually reports exactly what the issue is when there is a fatal. The most likely causes are either you haven't run Composer to generate the autoloader, or your require statement is not pointing to the correct relative path of the autoloader. I suggest you investigate these things, and if you have any questions, post them to a PHP subreddit or StackOverflow, as this is not a general PHP language/dev environment help forum.

**Comment by lerotham** [comment]
Thank you !

Ok, the problem was that I still had my old version of php 5.6. I had installed php 7.3 but not removed the old one. When I typed php --version, it was indicated php 7.3, but I suppose that Apache was still using the 5.6.

So I purged it and now it works !
