### ISSUE TITLE
Organizing Regressions

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#32]
Since a lot of the typical regression types are linear least squares, with some sort of translation, what do you think about using the PHP trait function to make this available? Once Matrix operations are complete, we could define a trait which contains the least squares matrix operations. Then each type of regression could do their translation, send the code to the trait computation, and then translate the results.

This would allow power, log, linear, and multiple linear to all use the same "complex" math to get their parameters, without having to extend a linear base class, or force the least squares function upon the parent Regression class.
Example:

    trait LeastSquaresRegression
    {
        function leastSquares($ys, $xs)
        {
            $X = new Matrix($xs);
            $y = new Matrix($ys);
            $(XᵀX)⁻¹Xᵀy = $X->transpose->mult($X)->inverse()->(mult($X)->transpose())->mult($y);
            return $(XᵀX)⁻¹Xᵀy;
        }
    }

    Class PowerLaw extends Regression
    {
        use LeastSquaresRegression;
        function calculate()
        {
            $transformed_y = array_map('ln', $ys);
            $transformed_x = array_map('ln', $xs);

            $betas = this->leastSquares($transformed_y,$transformed_x)

            // These might be backwards.
            $this->m = exp($betas[0]);
            $this->b = $betas[1];
        }
    }

**Comment by markrogoyski** [comment]
Good idea. I like it. It will reduce code duplication. I'll continue working on the Matrix class.

**Comment by Beakerboy** [comment]
There's a pull request for this.
