### ISSUE TITLE
Using the spaceship operator (<=>) instead of signum

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#322]
I was reading an article on newer PHP 7 features and came across the spaceship operator. It’s a comparator that returns -1, 0, or 1 if the left value is less than, equal to, or greater than the right value. So it seems that `Special::sign($x)` is equivalent to `$x <=> 0`. Since there’s a native operator, maybe we should standardize in using it in the code and just provide the `Special::sgn()` function for convenience.

**Comment by markrogoyski** [comment]
Yeah. Spaceship operator comes from Perl. It's been around a long time in Perl. It is new to PHP in version 7. Signum (sgn) should use that. I wonder why I didn't use it to start with on the signum function (I used to program Perl full time, I should have known better, lol).

I still like using named functions to give meaningful context of why you are doing things, but the named functions' implementation should definitely use modern language features like this. If a math definition of something calls out to use the signum (sgn) function, I'd use the named ```Special::signum``` in that case. But if it is like some other kind of comparison or something that isn't necessarily related to the mathematical usage of the signum function, then sure, just use ```$a <=>$b``` inline in that context for conciseness.
