### ISSUE TITLE
Update PHPCS Rule to Enforce PSR-12 Style

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#329]
We have a bunch of operator spacing errors on PSR-12. They can be automatically fixed.

**Comment by markrogoyski** [comment]
It looks like PHP Code Sniffer has not been updated yet. As soon as that is updated I'll add it to the Travis CI job and add additional auto lint shortcuts.

**Comment by markrogoyski** [comment]
It looks like Code Sniffer does have preliminary support for the PSR-12 ruleset. I'll update the coding standard and run PHP Code Beautifier and Fixer on the codebase. Like you mention, it looks like it is mostly spaces around arithmetic operators.

**Comment by markrogoyski** [comment]
I've updated all the code and updated the coding standard rule for the linter and CI system going forward. I'm not yet used to seeing the exponentiation (**) operator with spaces around it but that's the thing with a standard style guide--nobody likes every rule, but everybody likes that there are rules.

Thanks for letting me know that PSR-12 was finally accepted.
