### ISSUE TITLE
Array Functions?

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#34]
Have you thought about creating array functions for some of the common array_maps that are done. I'm thinking things like array_add, array_subtract, array_square, array_multiply, stuff like that. Take two arrays of the same length, and add, subtract, etc, item-by-item. It could keep everything more readable.

Just an idea. I know it's not "math" per se, but more convenience. PHP already has array_sum, so you could think of it as an extension to that. Go ahead and close this if you think it's a bad idea.

**Comment by markrogoyski** [comment]
PHP also has array_product: http://php.net/manual/en/function.array-product.php

This is not a bad idea. Especially things like squaring tends to get done a lot. 
Maybe a namespace Math\Functions\Map.

I'll think about the best way to implement it so it is clear.

**Comment by Beakerboy** [comment]
By array_multiply, I meant more 

    array_map(
        function($x,$y){
            return $x * $y;
        },$xs, $ys);

**Comment by markrogoyski** [comment]
Yeah. Map against two arrays to combine into a single array.

**Comment by Beakerboy** [comment]
There is a Math concept known as a Map, like in graph theory, so Math\Functions\Map might be too generic.

**Comment by markrogoyski** [comment]
I added two classes:
Math\Functions\Map\Single
Math\Functions\Map\Multi

The Multi functions will map over two or more arrays. No limit to how many arrays you can map against. Result is always reduced to a single array.

I imagine GraphTheory would have its own namespace, so no name collision to worry.

**Comment by Beakerboy** [comment]
Looks good. I'll use them and replace existing maps as I come across them.
