### ISSUE TITLE
Goal seek?

### ISSUE THREAD

**Issue by kman2013** [markrogoyski/math-php#357]
Not an issue - just a question
is there a function in your library that can simulate the Goal Seek function of Excel?
if so which one?
thanks!

**Comment by markrogoyski** [comment]
Hi @kman2013,

I'm not familiar with Goal Seek in Excel, but briefly looking at it, it seems like it might resemble a root finding function. If that is the case, you may be able to use something that is in `MathPHP\NumericalAnalysis\RootFinding` to do the same thing. I'll learn a little more about Goal Seek and get back to you.

**Comment by Beakerboy** [comment]
Yeah, it’s basically a root-finding process. You feed in some function that takes in an input and a “goal”, and the goal-seek will find the input that produces the goal.

**Comment by Beakerboy** [comment]
If you want something more complex, like Excel’s Solver, that would require a minimization method or root finding using Jacobian matrixes. We don’t have THAT yet, but you should be able to do a univariate function.

**Comment by Beakerboy** [comment]
One potential enhancement for the existing newtons method process, would be to allow a user to add a callback function for the derivative. Instead of evaluating the provided call back at two values to estimate the derivative it could be calculated directly.

**Comment by kman2013** [comment]
> Yeah, it’s basically a root-finding process. You feed in some function that takes in an input and a “goal”, and the goal-seek will find the input that produces the goal.

do you have an example of how to implement it?
most of the time I'm looking to solve for a required rate of return - knowing the end value what rate would you need to earn in order to arrive at that value (with a consistent cash flow)

**Comment by Beakerboy** [comment]
```php
<?php

use MathPHP\NumericalAnalysis\RootFinding;

$compound = function($initial, $rate, $periods){
    return $initial * $rate ** $periods;
};

$found_rate = RootFinding\NewtonsMethod::solve($compound, [5, 1.07, 5], 10, 1E-4, 1);
```

**Comment by kman2013** [comment]
thanks!
I'll give that a go :)

**Comment by kman2013** [comment]
oh wow I think that is it!
I tried in Excel and compared - looks good
I had to do a 1-foundrate though but other than that the result was matching
thank you so much!!!

**Comment by kman2013** [comment]
so, one further wrinkle - and not sure if this will handle it - what if the cash flow was for only 20 years but I wanted to know the value out to year 50?

**Comment by Beakerboy** [comment]
I don’t know what financial equations look like. I would have thought it was just a matter of changing a 20 to a 50.

**Comment by kman2013** [comment]
[testGS.xlsx](https://github.com/markrogoyski/math-php/files/3863465/testGS.xlsx)
I made a sample file to show - in columns c-e is what the goal from math-php is doing - so it is one payment of a 14564.6 growing to the amount at year 50 - it correctly shows the rate of 9.68%, however I would like it to do 20 years of payments of 14564.6 to arrive at a result at year 50 - and determine what rate I would need to use to get that result. In Excel columns G-J show that version - with the rate of 4.03% being the result.

**Comment by Beakerboy** [comment]
Your left column looks like it’s just a simple compound interest calculation, which is what I pasted above. You don’t actually need a goal seek for this, since everything can be calculated directly. If Final = initial * rate ^ periods...rate = (final/initial)^ (1/periods).

The data on the right with multiple cash flows cannot be directly calculated, but root-finding should work. Is this where you were having problems with IRR? I thought the MathPHP IRR function already uses root-finding to get the answer.

I would naively just do some sort of loop:

```php
$compound = function ($rate) {
    $total = 14574.6;
    for ($i=1;$i<20;$i++){
        $total = $total * $rate + 14574.6;
    }
    $total = $total * $rate ** 30;
    return $total;
}
 $found_rate = RootFinding\NewtonsMethod::solve($compound, [1.07], 1480202.73, 1E-4, 0);

**Comment by kman2013** [comment]
yes the left hand side was just to confirm what the PHP code was doing - agree goal seek is not needed there - the right hand side is the goal seek I need to emulate. I'll give this a try tonight.
So you think the IRR function should be able to calculate this result? hmmm interesting - I'll try that as well.
thank you!

**Comment by Beakerboy** [comment]
> So you think the IRR function should be able to calculate this result? hmmm interesting - I'll try that as well.

I thought you’ve been asking similar questions about IRR over the past couple of days. I’ve never used the Financial functions, but I was assuming a 50 element array with $array = [14574, 14574, 14574, (repeated 20 times), 0, 0, 0, (repeated 30 times)] would give you the right answer.

**Comment by kman2013** [comment]
the IRR questions were different but yes I did ask about that as well
I tried using the array
$found_rate = RootFinding\NewtonsMethod::solve($compound, [14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,14574.6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 1.05, 50], 1480202.73, 1E-4, 1);
result returned:
NAN%

**Comment by kman2013** [comment]
I just tried using the IRR function with the data - the results from the math php is matching the results from the Excel goal seek
I think that is what I need!! 
thank you so much for your time - I really do appreciate it.

**Comment by Beakerboy** [comment]
The array in the second parameter of the solve function is a list of arguments to be called to the callback function. You received an error because the function saved as $compound was not expecting those 50 inputs.

**Comment by Beakerboy** [comment]
This user's particular problem has been solved. Should this be closed, or do you want to keep it open for the Jacobian discussion?

**Comment by markrogoyski** [comment]
Let's close it. Thanks for revisiting this and verifying the status.
