### ISSUE TITLE
Optimized median finding algorithm

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#36]
Something interesting I found. For a large dataset, a full sort would take a lot more time than is needed to just find the median.

http://www.cs.cornell.edu/courses/cs2110/2009su/Lectures/examples/MedianFinding.pdf

**Comment by markrogoyski** [comment]
That's interesting to see there is a linear-time method to do this. PHP uses quicksort for its sorting so on average it is O(nlogn), which is usually what you aim for. For now I think I'd like to concentrate on adding features and maintaining clear code. But if you want to implement this you can always do a pull request. Also, in PHPDoc there is an @todo tag you can use as a reminder of future points of improvement.
https://phpdoc.org/docs/latest/references/phpdoc/tags/todo.html
