### ISSUE TITLE
Typo in quadratic function name

### ISSUE THREAD

**Issue by jacek77** [markrogoyski/math-php#370]
There is function 'quadratic' in Algebra class but in readme it is called 'quadradic'.

**Comment by markrogoyski** [comment]
Hi @jacek77,

Thanks for your interest in MathPHP and wanting to improve it.

Sorry if the spelling mistake in the documentation caused confusion. It will be fixed in the next release.

Thanks again.
Mark

**Comment by markrogoyski** [comment]
This has been fixed in the latest release. Thanks for the feedback and helping to improve MathPHP.
