### ISSUE TITLE
manhatten & euclidean distance / angle

### ISSUE THREAD

**Issue by nessor** [markrogoyski/math-php#377]
Maybe I am blind, but aren't the functions for determining the manhatten and euclidean distance and the angle between two vectors missing in vector calculus?Then I would implement them and open a PR

**Comment by markrogoyski** [comment]
Hi @nessor,

Thank you for your interest in MathPHP and wanting to improve it.

There is not yet a formal section for Geometric functions dealing with points and shapes and angles, etc. It's on the list of things to do eventually. I have not given a lot of thought to how to model these things yet, so if you have a proposal, please don't hesitate to let us know what you are thinking.

Thanks,
Mark

**Comment by nessor** [comment]
Hi Mark,

I'm thinking of sth. like this:
```
$A = new Vector([1, 2]);
$B = new Vector([2, 4]);

$A->manhattanDistance($B) // 3
$A->euclideanDistance($B) // 2,23607

$A->angle($B) // 0
```

with an implementation of this:
![image](https://user-images.githubusercontent.com/3463261/81373275-9f7ab980-90fc-11ea-97de-11198cf06bf8.png)
