### ISSUE TITLE
Spearmans Rho

### ISSUE THREAD

**Issue by docdik** [markrogoyski/math-php#380]
Hi
I'm constructing a correlation martix using the Spearmans Rho function.   I think you may have an error in this function.   My test data using your function gives a different answer from the JASP statistical package I use to test and https://www.socscistatistics.com/tests/spearman/default2.aspx.    Your test data does give the correct answer comparing with this package but I wonder if you should try a few other datasets.
Pearson's correlation is spot on.
Cheers
Richard

**Comment by markrogoyski** [comment]
Hi @docdik,

Thanks for your interest in MathPHP and wanting to improve it.

Can you provide some example data sets and the answer you think is correct and how it differs from MathPHP's calculation? This will be helpful to investigate and see if we can reproduce what you are seeing.

Thanks,
Mark

**Comment by docdik** [comment]
Hi Mark,  yes no probs,  Hope I am not wasting your time (i.e me messing
up!) csv is attached with data and the screen shot is from JASP, the
coloured Matrix is mine using  $rho = Correlation::spearmansRho($x,
$y);      Also included is my table for pearson's r which agrees with
JASP.   only thing I can think might be wrong is rank order and ties,  but
I have not looked at your function yet.
cheers
Richard




[image: Screenshot 2020-07-06 at 21.23.33.png]
[image: Screenshot 2020-07-06 at 21.37.47.png]
[image: Screenshot 2020-07-06 at 21.41.50.png]

**Comment by markrogoyski** [comment]
I don't think the screen shot was inserted into the post. Could you post the raw values for the inputs and the expected output?

**Comment by docdik** [comment]
<img width="502" alt="Screenshot 2020-07-06 at 21 23 33" src="https://user-images.githubusercontent.com/8442770/86642695-02d97880-bfd4-11ea-8882-04a24449f90a.png">
<img width="355" alt="Screenshot 2020-07-06 at 21 37 47" src="https://user-images.githubusercontent.com/8442770/86642729-0a008680-bfd4-11ea-9bf9-ce2e4275c922.png">
<img width="314" alt="Screenshot 2020-07-06 at 21 41 50" src="https://user-images.githubusercontent.com/8442770/86642738-0cfb7700-bfd4-11ea-9613-9af08d515d4d.png">


B1 | B2 | B3 | B4
2.5 | 2.25 | 6 | 4
2.5 | 2.75 | 7 | 6
2.5 | 2.75 | 8 | 3
3 | 2.25 | 3 | 2
3 | 2.25 | 6 | 9
2.5 | 3.25 | 5 | 7
2.25 | 2 | 4 | 8
2.75 | 2 | 6 | 9
2 | 2.75 | 6 | 5
2.75 | 1.25 | 4 | 4

**Comment by docdik** [comment]
Ha that worked :)

**Comment by docdik** [comment]
2.5, 2.5, 2.5, 3, 3, 2.5, 2.25, 2.75, 2, 2.75
2.25, 2.75, 2.75, 2.25, 2.25, 3.25, 2, 2, 2.75, 1.25
6, 7, 8, 3, 6, 5, 4, 6, 6, 4
4, 6, 3, 2, 9, 7, 8, 9, 5, 4

this may be easier

**Comment by markrogoyski** [comment]
Hi @docdik,

Thanks for the sample data. I used R to test the results and got different answers than that MathPHP is producing, so I think you are right, there may be something not right here. I will investigate this. Thanks for bringing it to my attention.

For reference, here is what R produced for some of them:
```R
> b1 <- c(2.5, 2.5, 2.5, 3, 3, 2.5, 2.25, 2.75, 2, 2.75)
> b2 <- c(2.25, 2.75, 2.75, 2.25, 2.25, 3.25, 2, 2, 2.75, 1.25)
> b3 <- c(6, 7, 8, 3, 6, 5, 4, 6, 6, 4)
> b4 <- c(4, 6, 3, 2, 9, 7, 8, 9, 5, 4)
> cor.test(b1, b2, method='spearman')

	Spearman's rank correlation rho

data:  b1 and b2
S = 226.41, p-value = 0.2896
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
-0.3721858 

> cor.test(b1, b3, method='spearman')

	Spearman's rank correlation rho

data:  b1 and b3
S = 206.92, p-value = 0.4787
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
-0.254073 

> cor.test(b1, b4, method='spearman')

	Spearman's rank correlation rho

data:  b1 and b4
S = 167.09, p-value = 0.9723
alternative hypothesis: true rho is not equal to 0
sample estimates:
        rho 
-0.01266457 
```

**Comment by markrogoyski** [comment]
Hi @docdik, 

The issue seems to be when the ranks are not all distinct. When there are tied ranks a different formula must be used. I will work on a fix and let you know when it is ready.

Thanks again for sharing your findings. We'll get this fixed.

Mark

**Comment by docdik** [comment]
Hi Mark,  thanks,  I wondered if that was the case,  I had to do something similar writing a programme for the Mann-Whitney test.
All the best
Richard

**Comment by markrogoyski** [comment]
Hi @docdik,

[Version 1.2.0](https://github.com/markrogoyski/math-php/releases/tag/v1.2.0) has been released and fixes Spearman's Rho to do the right calculation when there are ties in the rank variables. Your sample data now all computes the correct rho result.

In making this fix, I refactored out the ranking computations into independent functionality that can now be used directly. If your are interested, those functions may be used like this:

```php
// Ranking of data
$values                       = [1, 2, 2, 3];
$ordinal_ranking              = Distribution::ordinalRanking($values);              // 1, 2, 3, 4
$standard_competition_ranking = Distribution::standardCompetitionRanking($values);  // 1, 2, 2, 4
$modified_competition_ranking = Distribution::modifiedCompetitionRanking($values);  // 1, 3, 3, 4
$fractional_ranking           = Distribution::fractionalRanking($values);           // 1, 2.5, 2.5, 4
```

Spearman's Rho makes use of the fractional ranking function.

Thank you again for bringing this issue to our attention and apologies that it was computing the wrong result when there were ties. Please try it again and report back if you still see any issues. You have definitely helped improve the quality by opening this issue.

Thanks again.
Mark

**Comment by docdik** [comment]
Many thanks Mark
That look very useful indeed, I'll update things next week.  Busy playing
with ANOVA at the moment for another set of tests I need to do.
all the best
Richard
