### ISSUE TITLE
Invalid PHP syntax in financial code examples

### ISSUE THREAD

**Issue by artem-fokanov** [markrogoyski/math-php#395]
Hi

There are several typos in [financial code samples](https://github.com/markrogoyski/math-php#finance) that leads to syntax errors such as: 
- Missing double colons for `Finance::irr` and `Finance::mirr` methods
- missing namespace resolution for `Finance::rate` and `Finance::profitabilityIndex` methods.

![issues](https://user-images.githubusercontent.com/14099629/96503369-ca486c80-125b-11eb-90dc-55e8d5e60da8.jpg)

Thanks!

**Comment by markrogoyski** [comment]
Hi,

Thanks for your interest in MathPHP. You are right, there are some typos in the README documentation. I will fix these in the upcoming release.

Thanks for pointing this out.
Mark

**Comment by markrogoyski** [comment]
These have been fixed and will be reflected on the home page in the next release.

Thanks again!
Mark

**Comment by artem-fokanov** [comment]
Thank you! 

Artem

**Comment by markrogoyski** [comment]
This has been fixed in the latest release, v1.6.0.
