### ISSUE TITLE
Regression through a point

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#4]
The regression library should also include regression through a point, like RTO (regression through the origin). However, this technique has different calculations for r, and different confidence interval calaculations.  Would it make sense to have an abstract Regression class which defines what is needed and available for a regression, and the different types (SLR, RTO, log, power) would each extend this abstract class and implement the required functions?

**Comment by markrogoyski** [comment]
Hi,
I agree with your comment in the other issue thread about making Regression an object with methods, and then if the calculations for other things like r are different, then the individual Regression classes can handle it.

The one design goal I'm trying to keep with is to keep things simple and easy. So as long as we don't go overboard with needing to instantiate multiple objects and setup then I think it is a good refactor.

**Comment by Beakerboy** [comment]
A similar concept can be applied to distributions. Here's a file I made for the normal distribution (instead of the standard table that you have)
    
    <?php
    namespace Math\Distribution;
    use Math\Functions;
    class NormalDistribution extends Distribution {
      public static function PDF($x, $μ, $σ²) {
        $π = \M_PI;
        $pdf = exp(-1 * ($x - $μ) ** 2 / 2 / $σ²)/(sqrt(2 * $σ² * $π));
        return $pdf;
      }
      public static function CDF($x, $μ, $σ²) {
        $cdf = (1 + Functions::erf(($x - $μ) / sqrt(2 * $σ²))) / 2;
        return $cdf;
      }
    }

**Comment by Beakerboy** [comment]
Regression Through A Point is in the latest pull request. I'll add a convenience class for regression through the origin.

**Comment by Beakerboy** [comment]
There's a pull request for the unit test for this class.
