### ISSUE TITLE
Installation on shared host

### ISSUE THREAD

**Issue by japetos** [markrogoyski/math-php#411]
Hello,

is it possible to use math-php without installing it via composer? I have a shared host and i only have the option to upload. What do i have to to, to avoid having issues with name spaces, etc.?

**Comment by Beakerboy** [comment]
Something like this should work:
https://stackoverflow.com/questions/39571391/psr4-auto-load-without-composer

**Comment by markrogoyski** [comment]
There are two basic options:
- Run composer locally on your computer and then upload the vendor directory that is created that contains the MathPHP library and the composer autoloader
- Write your own autoloader

The link @Beakerboy provided shows examples of how to do this.
