### ISSUE TITLE
Basic Linear Algebra Subroutine coverage

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#43]
If you are working on linear algebra, do you think the library should cover the BLAS standards?
www.netlib.org/blas/

**Comment by markrogoyski** [comment]
Looking around the Web are libraries that implement this, it seems like low-level hardware libraries and such. It's definitely a good list of functions to implement, but for now, I would not worry about trying to conform to this standard, and instead, just concentrate on adding useful features. I'll close this for now, but it is worth considering again in the future when the linear algebra section is more feature complete.
