### ISSUE TITLE
Dealing with NANs

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#435]
The R sources that I've been reviewing spend a fair amount of code in each function managing how to handle NAN as input, and when to properly output NAN. It seems we use exceptions instead of NAN on the output side. Is this best long term when IEEE 754 already defines a way to deal with this in floating point numbers? Is this something worth considering? Since NAN is a float, typesetting on inputs will not prevent NAN from entering some of our functions, so we should probably decide how to handle these situations.

**Comment by markrogoyski** [comment]
[Version 2.5.0](https://github.com/markrogoyski/math-php/releases/tag/v2.5.0) implemented `NanException` as discussed.
