### ISSUE TITLE
Psalm does not understand `number` pseudo-type

### ISSUE THREAD

**Issue by aboks** [markrogoyski/math-php#470]
This issue is a follow-up to the comment in https://github.com/markrogoyski/math-php/issues/456#issuecomment-1538182370. When using math-php in a project that uses Psalm for static analysis, any usage of a method that has a `number` pseudo-type as a type hint results in an error, as Psalm does not recognize `number` as a type.

Some examples of this are illustrated by the sample project I created in https://github.com/aboks/math-php-psalm-example. The file `example.php` contains some sample usage of math-php linear algebra classes that use the `number` type. If you run `composer install` and then run Psalm (v5.11.0) using `vendor/bin/psalm`, Psalm gives the following errors:

> ERROR: InvalidArgument - example.php:6:24 - Argument 1 of MathPHP\LinearAlgebra\NumericMatrix::__construct expects array<array-key, array<array-key, MathPHP\LinearAlgebra\number>>, but list{list{1, 2, 3}, list{4, 5, 6}} provided (see https://psalm.dev/004)
$A = new NumericMatrix([[1, 2, 3], [4, 5, 6]]);
>
> ERROR: InvalidArgument - example.php:9:30 - Argument 1 of MathPHP\LinearAlgebra\NumericSquareMatrix::__construct expects array<array-key, array<array-key, MathPHP\LinearAlgebra\number>>, but list{list{1, 2}, list{3, 4}} provided (see https://psalm.dev/004)
$B = new NumericSquareMatrix([[1, 2], [3, 4]]);
>
> ERROR: InvalidArgument - example.php:12:17 - Argument 1 of MathPHP\LinearAlgebra\Vector::__construct expects array<array-key, MathPHP\LinearAlgebra\number>, but list{1, 2} provided (see https://psalm.dev/004)
$v = new Vector([1, 2]);

(As an aside for those not familiar with Psalm: the problem is not in `list` vs. `array`, a `list` is a valid subtype of `array`. The issue here is purely about Psalm not understanding `number` and interpreting it as classname.)

For me, this issue is not about having math-php itself fully analysed and checked by Psalm. While that could probably benefit  the project as well, in my view a worthwhile first milestone would be that projects that consume the math-php library and use Psalm are able to use math-php in their code without errors.

**Comment by markrogoyski** [comment]
Hi @aboks,

[Version 2.8.1](https://github.com/markrogoyski/math-php/releases/tag/v2.8.1) has been released which has numerous internal improvements to improve static analysis runs of Psalm while maintining PHPStan 100% passing.

There is still more work to get Psalm passing for various checks, but the number type checks should be fixed, as well as numerous other invalid argument-type mistakes.

Please give the latest version a try. If there are still Psalm static analysis issues you need addressed please post them here. As a long term goal for version 3.0 of the library I am going to try to get Psalm passing and running in CI to prevent regressions.

Thanks again for the feeback.
Mark

**Comment by aboks** [comment]
Hi @markrogoyski, works like a charm for our purposes! Thanks for the new release.
