### ISSUE TITLE
Student T Distribution CDF for Negative t Value

### ISSUE THREAD

**Issue by markrogoyski** [markrogoyski/math-php#55]
It seems like the StudentT CDF might be returning the upper cumulative rather than the lower cumulative for negative t values.

For example, compare the output of this calculator for x = -1 and v = 2
(http://keisan.casio.com/exec/system/1180573203)
lower cumulative = 0.211324865405187117745
upper cumulative = 0.788675134594812882255

The StudentT CDF seems to match that calculator's upper cumulative for negative values, whereas it matches the lower cumulative for positive values.

**Comment by Beakerboy** [comment]
Looking at the equation, the only place t shows up in in the denominator of x(t), where it is squared. therefore, CDF(x, v) == CDF(-x,v).  I guess we could change it to
    
    if (t == 0) return .5
    if (t > 0) return 1-.5 * I(x, v / 2, .5);
    if (t < 0) return .5 * I(x, v / 2, .5;

**Comment by Beakerboy** [comment]
Fixed in pull request
