### ISSUE TITLE
Floating point comparisons

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#58]
I'm working on making a small change to the Continuous::inverse() function. Right now it's hard-coded with an initial guess of .5.  This is fine for distributions which either hang out between 0 and 1, or have a median around 0, but if it's a normal distribution with a mean far away from 0, the slope at .5 will be nearly 0.

I'm trying to use the new mean, median, and mode functions to populate the initial guess, but when the initial guess = 0 for StudentsT, the slope calculation says the slope is zero. I have to dig into the code more to see where the evaluation is crapping out, but it could be with some of our comparisons using floating point numbers.

Do we want to define an epsilon for precision, and replace $a == $b with abs(($a - $b) / $b) > $epsilon?
or use bc_comp($a, $b,) == 0 ? 
Any thoughts?

**Comment by markrogoyski** [comment]
From my experience, if the numbers are very precise floats, the regular comparison operators work as expected even with really small numbers like: 1.0E-31 < 2.0E-31.

Things start to get fuzzy when you have something like:
$a = 0.33333333333333;
$b = 1/3;
if ($a < $b) ...

The BC Math extension is supposed to handle floating point precision better, but it has its own issues--mainly that you have to pass all values to it as strings. So I don't think you can even send it 1/3 as a value and have it work as expected.

Anyways, if you want to use bccomp from the BC Math library, you have to consider that BC Math is a PHP extension, and is not guaranteed to be installed in every PHP installation. Furthermore, it is not a Composer package, it is a PHP extension, so if someone is using a cheap GoDaddy Web host where they don't control the server and it isn't installed, they would not be able to use the library if you depend on it.

So any place you would want to use bccomp, you first have to check if they have the extension installed:
if (extension_loaded('bcmath')) {
  $result = bccomp($a, $b);
} else {
  $result = $a < $b;
}
Something like that, where you fall back to the standard comparison operators if the extension is not present.

So, whether you want to use BC Math to improve floating point precision or not, it will still have to work normally in the case that BC Math is not installed.

Also FYI, the bccomp method returns a value, not a bool. So you have to check the value similar to how the Perl (and newly PHP) spaceship operator <=> works.

Make sense?

**Comment by Beakerboy** [comment]
I just had a small epiphany...the derivative of the CDF of a distribution is the PDF, so I don't need a numerical derivative, I can just evaluate the PDF at my guess, and use that to get the next approximation.
