### ISSUE TITLE
Accuracy of gamma function

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#6]
Instead of always using one of the estimations, why not use the definition of gamma when appropriate:

    static function Γ($n){
      $π = \M_PI;
      if (is_int($n)){
        return self::fact($n - 1);
      }

    // floating point safe comparison
      if(round($n * 2, 0) / 2 / $n == 1){
        $x = round($n - .5, 0);
        return sqrt($π) * self::fact(2 * $x) /(4 ** $x) / self::fact($x);
      }
      return self::ΓStirling($n);
    }

**Comment by markrogoyski** [comment]
Can you provide a link to something showing this definition:
`return sqrt($π) * self::fact(2 * $x) /(4 ** $x) / self::fact($x);`

Thanks.

**Comment by Beakerboy** [comment]
https://en.wikipedia.org/wiki/Particular_values_of_the_Gamma_function

**Comment by Beakerboy** [comment]
In case you're interested, I have a math library I threw together several years ago, that I was beginning to reorganize. However, I figured someone might already have something in composer, which is where I found your library. Yours has the most overlap with mine. I've started moving what I have into github [here](https://github.com/Beakerboy/math-php7/tree/master/Math). Check it out and let me know what you think.

**Comment by markrogoyski** [comment]
Thanks for the link and the feedback. I've updated the gamma function to use the formula for half integers.

**Comment by markrogoyski** [comment]
Btw, would you like to contribute to this math library? If so, if there is something specific you'd like to work on let me know.

**Comment by Beakerboy** [comment]
Yeah, I'd like to contribute.  However, I'm a sucky programmer...I'm awful at documenting, I've never done a unit test, I don't know whitespace standards, and I don't know PHP7 yet...the list goes on. I just liked what I see in your library, but it doesn't have everything I'd need, and it's not organized the way I would have done it. For example, some distributions are in Statistics\Distribution, and some in Probability\Distribution. 
I also need inverse T. I calculate it with Newton's method on the CDF. Look at Solver/Newton.php and Distribution\Distribution.php.

So...All-in-all, I'd love to move to a library that is in composer so there are more eyes on the code. If you want me to add in what I have, I can do that with some pull requests. Or, feel free to steal anything at the project link I gave you. Another "stealworthy" function that I have is the regularized incomplete beta function. It's used in the CDF for student-T and the F distribution. 

My first major suggestion would be for more class hierarchy on Regressions and Distributions.

Distributions
-Continuous
--Normal
---StandardNormal
---StudentT
-Descrete
--Binomial

**Comment by markrogoyski** [comment]
Please do a pull request. We definitely need things like:
 - regularized incomplete beta function and incomplete beta function
 - lower and upper incomplete gamma function
 - hypergeometric function
 - etc.
These will allow implementation of many more distributions like you said.

Don't worry if it is not perfect. We can refactor, add documentation and unit tests, etc.

Thanks for your help.

**Comment by Beakerboy** [comment]
Added a pull request for two functions. Despite the fact that I suck at documentation, would you be able to add something at the top of a few class files explaining the scope of what that class should contain? The name "calss RandomVariable" makes me think it's a random number generator. Would it make sense to split up the functions into ones that operate on one vector(average, stdev), versus ones that operate on two(covarience, r)?

The erf function is neither, and accepts only a singular $x argument. I think it would be best placed in Functions.php

**Comment by markrogoyski** [comment]
I'll add some class documentation to RandomVariable. And I'll move erf to Functions. Let me think about splitting up functions.

**Comment by markrogoyski** [comment]
Question about the regularized incomplete beta function. Please see:
https://github.com/markrogoyski/math-php/issues/16
