### ISSUE TITLE
Sum of squares on regression through a point

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#63]
https://online.stat.psu.edu/~ajw13/stat501/SpecialTopics/Reg_thru_origin.pdf
 page 78

These sum of squares calculations are different when regressing through the origin.

I think the regression set-up needs to be re-thought. Simple linear regression, through a point, and multiple linear will all use the exact same matrix math to calculate the parameters. Also, plenty of other functions can be linearized and passed through a linear least squares calculation, with or without a constant.

for example V(S) = Vm *S / (Km + S) can be linearized to 1 / V = Km / Vm * 1/S + 1/Vm

or y = m ** x can be linearized to a regression through the origin: ln(y) = ln(m) * x
The regression through origin, or point, will have some different stats than simple-linear-regression. I need to see how R handles it, but in Excel, things like the standard error are not transformed back to original scale when doing a power or log fit...which reddit and stack excahnge says is correct, but I don;t understand the argument.

When I get the Jacobian done, we can support non-linear least squares regression, where we truly fit to the source function. Linearizattion can change the leverage of points along the curve, making some more influential than they should. Although, linearization and using weighted least squares can compensate for this.

**Comment by markrogoyski** [comment]
Thanks for the link.

Before reverting the change, I have a question:
What if you force the regression through a point other than the origin? Are the calculations the same as if through the origin, or for a normal OLS regression?

**Comment by Beakerboy** [comment]
I can't think of a reason why they would be different. The"values" will be different based of choice of 'forcing point', but the equations should be the same.

**Comment by markrogoyski** [comment]
The LinearThroughPoint regression is using the same LeastSquares Method as regular Linear. Is that OK or does it need to have a different sum of squares calculations?

**Comment by Beakerboy** [comment]
It should be correct. If the degrees of freedom are correct, the rest of the math should work out. I'll put in some unit tests to make sure.

**Comment by Beakerboy** [comment]
You're correct, it was wrong. I fixed the equation, but have to do unit tests. SStot can be generalized to be SSe+SSreg, but SSreg needed to be changed.

**Comment by Beakerboy** [comment]
I added some unit tests. pull request submitted
