### ISSUE TITLE
Vandermonde matrix

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#66]
https://en.wikipedia.org/wiki/Vandermonde_matrix

Providing an array and an int, produce this matrix. I don't know my design patterns, so would extending Matrix and adding some sort of factory work here?

    public function __construct(array $R, int $n)
    {
        for ($i=0;$i<$n;$i++)
        {
            $A[] = Single::pow($R, $i);
        }
        $this->A = $A->transpose();
    }

**Comment by markrogoyski** [comment]
I was also thinking about maybe making RowVector and ColumnVector subclasses. So it may make sense to have a VectorFactory and MatrixFactory that can return the right kind of object based on the inputs. I'll think about it and come up with something.

**Comment by Beakerboy** [comment]
My understanding is, a 'row vector' is a matrix, with only one row, while an actual vector is a 1D construct, and does not have height or width, just length....an array.

**Comment by Beakerboy** [comment]
Pull request submitted
