### ISSUE TITLE
Child constructor differs from parent

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#68]
from the PHP manual:

> Unlike with other methods, PHP will not generate an E_STRICT level error message when __construct() is overridden with different parameters than the parent __construct() method has. 

Does this mean it's OK do do this? The LinearThroughPoint constructor differs from its parent.

**Comment by markrogoyski** [comment]
Yeah it works. Regular methods will trigger a warning if the interface is different, but the constructor is OK to do so.
