### ISSUE TITLE
Regexp error?

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#71]
I changed the least squares trait to use matrix math, and all the checks passed except 
Failed asserting that 'y = 1.000000x + -0.000000' matches PCRE pattern "/^y = \d+[.]\d+x [+] \d+[.]\d+$/".

Is the minus sign screwing things up?

**Comment by markrogoyski** [comment]
Try changing it to this:
^y = -?\d+[.]\d+x [+] -?\d+[.]\d+$

That will allow an optional minus sign before the slow and intercept.
