### ISSUE TITLE
Is coveralls broken, or disabled?

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#76]
The last few Pull requests have not had a coveralls summary attached. Also, the coveralls website says:

The file "src/Probability/Distribution/Continuous/Continuous.php" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.

**Comment by markrogoyski** [comment]
Nothing should have changed, but it definitely does not seem to be updating. I'll take a look.

**Comment by markrogoyski** [comment]
The individual build pages were working, and after poking around in those, it seems like the main build page is working again:
https://coveralls.io/github/markrogoyski/math-php

**Comment by Beakerboy** [comment]
thanks for looking into it. It's a nice service to have. Do you know how to add phpcs to the travis build to verify whitespace/formatting?

**Comment by markrogoyski** [comment]
I'll look into it.

**Comment by markrogoyski** [comment]
I'll open a new issue for phpcs.
