### ISSUE TITLE
Moving average (feature request)

### ISSUE THREAD

**Issue by ndabAP** [markrogoyski/math-php#79]
Please consider adding moving average.

Love your library. Thanks!

**Comment by markrogoyski** [comment]
Thanks for the feedback.
I added the following moving averages:
- Simple moving average
- Cumulative moving average
- Weighted moving average
- Exponential moving average

They are in the _Math\Statistics\Average_ namespace.
Usage is documented on the main page.

If you have any other feature requests, please create another issue.
Thanks again for the feedback.

**Comment by ndabAP** [comment]
That's just great!
