### ISSUE TITLE
Pearson's Coefficient of determination

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#8]
The equation you use is basically only valid for simple linear regression. I think it would make sense to add two equations, one for SSreg and SStot, and use the child's $this->evaluate() to calculate each when a user begins a regression. r² = SSreg/SStot; The Regression class could have a function getYhat which maps the Xs array through the evaluate() function. I think the Regression should have something like:

    public function getYhat(){
      return array_map (function($x){return $this->evaluate($x)},$this->xs);
    }
    public function getSSreg(){
      $Yhat = $this->getYhat();
      $ybar = average ($this->ys)
      return array_sum(array_map (function($yhatpoint){ return ($yhatpoint - $ybar) ** 2;},$Yhat));
    }

    public function getSStot(){
      return array_sum(array_map (function($y){ return ($y - $ybar) ** 2;},$this->ys));
    }

    public function r2(){
      return getSSreg() / getSStot();
    }

**Comment by Beakerboy** [comment]
Thinking about this, it would probably be good to determine how we want the inputs of evaluate() to be set up. If doing a multiple Linear regression (y=a+bw+cx), we will need to provide both a w and x to evaluate. This could be done by either evaluate(array(w,x)) or evaluate(w,x). 

Will Regression::xs be an array with two columns in this case. The existing function will work for the case where the function would accept an array, but if it's a series of parameters (the approach I prefer), we will probably have to use:

    public function getYhat(){
      return array_map (function($x){return call_user_func_array([get_class($this),'evaluate', $xs)},$this->xs);
    }

The Regression class will also have to use the '...' operator

**Comment by markrogoyski** [comment]
I think I follow. This seems like a good refactor.

Quick question, shouldn't r2 be: 1 - SSreg/SStot?
https://en.wikipedia.org/wiki/Coefficient_of_determination#Definitions

**Comment by Beakerboy** [comment]
SSres + SSreg  = SStot

r² = SSreg / SStot = (SStot - SSreg) / SStot = 1 - SSreg / SStot

you mixed up 'res' with 'reg'.

**Comment by markrogoyski** [comment]
Thanks for the clarification. My mistake. Thanks.

**Comment by Beakerboy** [comment]
There's a pull request for this.

**Comment by markrogoyski** [comment]
Pull request merged.

Question1: Do we also want to add SStot to the Regression class?

Question2: Are R and R2 valid for non-linear regression models? Should we move those methods to the Linear regression class instead of the base class?

**Comment by Beakerboy** [comment]
1: I will add SStot. I was waiting to see if you wanted to add the generic Sum of Squares first.
2: R² is defined as SSreg/SStot for at least all linear models....And the Log regression algorithm we use IS a linear fit. The log model is transformed to a linear equation, solved, then transformed back. This can actually lead to situations where the result is not the best fit, because the least squares are minimized on the transformed data, not the original data.

**Comment by Beakerboy** [comment]
SStot is in a pull Request.
