### ISSUE TITLE
Checking parameters...Test $p

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#94]
Distribution inverses will be given a $p, or $target parameter, which has the range [0,1]. Would it be best to add this to each distributions CONST, or is there a way that the parent can initialize this, and have the children add their distribution specific parameters?

**Comment by markrogoyski** [comment]
If the inverse function being used is the parent, then you could probably do something tricky like use self::CONST to access the parent's constant and static::CONST to access the child's, but if the inheriting child class has the inverse function overriding the parent, then there is no way to access the parent's variables if you've overridden them.

Probably simplest to just add it to each distributions' LIMITS const.

**Comment by Beakerboy** [comment]
I added checks on p to the children with their own inverse method. The parent method will be trickier so I added a @todo to it. The only way I can see the Continuous class checking the child's parameters for it to assume that they are in the same order (ie, $params[0] is the same as static::Limits[1])
